### ISSUE TITLE
Site images

### ISSUE THREAD

**Issue by blakadder** [blakadder/templates#1]
![image](https://user-images.githubusercontent.com/5904370/53397726-259f5a00-39a8-11e9-8a2a-b301393b8888.png)
![image](https://user-images.githubusercontent.com/5904370/53570017-c1c29000-3b65-11e9-9c41-4d8fcf2d2352.png)
![image](https://user-images.githubusercontent.com/5904370/53868501-793c2400-3ff6-11e9-9dd1-b2ab7a9c7748.png)

![image](https://user-images.githubusercontent.com/5904370/54072144-d5ad7680-4276-11e9-9c6a-6219b04917f8.png)

![image](https://user-images.githubusercontent.com/5904370/54396962-14975e00-46b5-11e9-82dd-dc95ac588e84.png)

![image](https://user-images.githubusercontent.com/5904370/54642319-92cc7980-4a94-11e9-8bbc-8a7450cecbfc.png)

![image](https://user-images.githubusercontent.com/5904370/54642725-9c0a1600-4a95-11e9-9f09-96c124d1a7bf.png)

![image](https://user-images.githubusercontent.com/5904370/54643115-6ca7d900-4a96-11e9-99a5-d139bde7f071.png)

![image](https://user-images.githubusercontent.com/5904370/54643685-c9f05a00-4a97-11e9-9b51-a99c2108b986.png)

![image](https://user-images.githubusercontent.com/5904370/54644416-85fe5480-4a99-11e9-8f0a-ece4a8640e45.png)

![image](https://user-images.githubusercontent.com/5904370/54646076-48e89100-4a9e-11e9-87fb-54b27ae024ab.png)

![image](https://user-images.githubusercontent.com/5904370/54647111-aaf6c580-4aa1-11e9-8da2-fab79ef32e4e.png)

![image](https://user-images.githubusercontent.com/5904370/54647463-dded8900-4aa2-11e9-9b8a-7b9ef4fe2c23.png)

![image](https://user-images.githubusercontent.com/5904370/54648203-9fa59900-4aa5-11e9-9701-f3586d9375da.png)

![image](https://user-images.githubusercontent.com/5904370/54648409-70dbf280-4aa6-11e9-8429-a784cf2c6750.png)

![image](https://user-images.githubusercontent.com/5904370/54648572-1727f800-4aa7-11e9-9f92-c19a1045e70a.png)

![image](https://user-images.githubusercontent.com/5904370/54649866-2a899200-4aac-11e9-93be-e1ae3d4c48be.png)

![image](https://user-images.githubusercontent.com/5904370/54650236-cbc51800-4aad-11e9-833d-b652c8df92cb.png)

![image](https://user-images.githubusercontent.com/5904370/54651586-d2ef2480-4ab3-11e9-9157-c56d3a427009.png)

![image](https://user-images.githubusercontent.com/5904370/54651712-5f014c00-4ab4-11e9-8622-8f4104632427.png)

![image](https://user-images.githubusercontent.com/5904370/54652058-b9e77300-4ab5-11e9-894e-01abc3802656.png)

![](https://github.com/untergeek/shared_images/blob/master/devices/powerstake/powerstake_esp12s.jpg)

![image](https://user-images.githubusercontent.com/5904370/54867860-8e9aa780-4d85-11e9-85fe-2f10138b7ed2.png)

![image](https://user-images.githubusercontent.com/5904370/54481150-5d742180-4831-11e9-8dea-6e1cbf6ef1bd.png)

![image](https://user-images.githubusercontent.com/5904370/55022165-5354de80-4ffa-11e9-95b5-80428ab68ded.png)

![image](https://user-images.githubusercontent.com/5904370/55142867-e2b6da80-513d-11e9-96f2-f10c0c38df50.png)

![image](https://user-images.githubusercontent.com/5904370/55217741-8cf73680-5200-11e9-9aed-3e78b8f108f2.png)

![image](https://user-images.githubusercontent.com/5904370/55259459-007f5f00-5266-11e9-94f8-cc2e6e09b963.png)

![image](https://user-images.githubusercontent.com/5904370/55288894-d8574380-53be-11e9-9738-0a801b0705b5.png)

![image](https://user-images.githubusercontent.com/5904370/55393418-7ec95300-553d-11e9-86d9-e765e2abb80d.png)

![image](https://user-images.githubusercontent.com/5904370/55464523-95ce7a80-55fb-11e9-9fb7-f51cf09b8177.png)

![image](https://user-images.githubusercontent.com/5904370/55464650-db8b4300-55fb-11e9-94d1-58188ad718c3.png)

![image](https://user-images.githubusercontent.com/5904370/55691622-34622f00-59a0-11e9-8f1d-8f4c8e649d66.png)

![image](https://user-images.githubusercontent.com/5904370/55704903-b91f6e00-59dd-11e9-86c4-5f378f30ec6d.png)
![image](https://user-images.githubusercontent.com/5904370/55705050-20d5b900-59de-11e9-93fb-c7c77ea7b658.png)

**Comment by blakadder** [comment]
![image](https://user-images.githubusercontent.com/5904370/53404371-d4966280-39b5-11e9-8ec8-a471ecd3178a.png)

**Comment by blakadder** [comment]
![image](https://user-images.githubusercontent.com/5904370/54481150-5d742180-4831-11e9-8dea-6e1cbf6ef1bd.png)

**Comment by melikyuksel** [comment]
Some images on the Template website seem to link directly to the submitted image link. Will these images be moved to a more permanent location in case of links being broken?

**Comment by blakadder** [comment]
No. In the template form it is explicitly stated to host the images somewhere else just because of that

**Comment by melikyuksel** [comment]
Okay, here's one then. ![LEPOWER](https://user-images.githubusercontent.com/10296053/54907967-d0763b80-4eb4-11e9-8684-eaca6e1ef06b.jpg)
