### ISSUE TITLE
youngzuth_SW02-02 template wrong.

### ISSUE THREAD

**Issue by HuangRicky** [blakadder/templates#1007]
https://github.com/blakadder/templates/blob/master/_templates/youngzuth_SW02-02

the correct one is template {"NAME":"SW02 2W","GPIO":[52,0,0,17,21,0,0,0,18,22,0,0,0],"FLAG":0,"BASE":18}

**Comment by blakadder** [comment]
What makes a button more correct than a switch?

**Comment by HuangRicky** [comment]
Because otherwise it will only turn on when you keep pressing the
physical button. If you release the button , light will be off.

**Comment by blakadder** [comment]
good point! will correct the template with yours. 

thanks
