### ISSUE TITLE
Is the SS311KWS AliExpress link still correct ?

### ISSUE THREAD

**Issue by demondev** [blakadder/templates#1013]
This page https://templates.blakadder.com/kinetic_switch_SS311KWS.html links this AliExpress product https://www.aliexpress.com/item/32953812650.html 

The image of the product on blakadder looks nothing like that given on AliExpress. Also the switch pic on AliExpress looks a lot like this unsupported item https://templates.blakadder.com/unsupported/loratap_SP311WST.html

**Comment by blakadder** [comment]
it is submitted that way

**Comment by demondev** [comment]
You are saying a third party provided this information to you and you created the template page ? Which implies you have no way of verifying this information ? 

It very much looks to me like the AliExpress seller has edited the item since the template page was created and if you bought the item now it would not be incompatible. There is no mention of the SS311KWS part number in the current listing,

**Comment by blakadder** [comment]
Nothing new, Amazon sellers do the same thing

**Comment by demondev** [comment]
What do you do with the template page in this case ? Remove the link ? Put a note about the link ?

**Comment by blakadder** [comment]
if its spotted by someone the dead/wrong link will be removed as in this case

**Comment by demondev** [comment]
Perfect, thanks.
