### ISSUE TITLE
Device mis-classifications?

### ISSUE THREAD

**Issue by meingraham** [blakadder/templates#102]
What characteristic in the template makes the [Shelly RGBW2](https://blakadder.github.io/templates/shelly_RGBW2.html) Miscellaneous and the [MagicHome](https://blakadder.github.io/templates/magichome_ZJ-WFMN-A_RGBW.html) not? What needs to be changed in the Shelly so that it's "together" with the other similar devices?

Should the Slampher  and the Elegant Choice E27/E26 be classified with the bulbs?

Mike

P.S. You've been a stranger lately. YOu must have a heavy work project load. Drop by Discord sometime :wink:

**Comment by blakadder** [comment]
The people submitting the device!

No

I am in Discord all the time

**Comment by meingraham** [comment]
I tried to look at the Shelly entry to see where to change it. I am happy to re-classify it but didn't see where that happens.

Mike

P.S. Discord - Cool. You're just quieter than before the summer holidays.

**Comment by blakadder** [comment]
No worries, I changed it as soon as I read this issue
