### ISSUE TITLE
new Teckin SP22 with T102/WR2 Tuya module based on RTL8710BN

### ISSUE THREAD

**Issue by hochwasser** [blakadder/templates#105]
Hello,

please add a warning to the SP22 Teckin plugs cause they have changed the WiFi module inside.
I could not change the firmware with tuya-convert so I opened one up and found a [T102/WR2](https://docs.tuya.com/docDetail?code=K8uhkbx75kg7y) WiFi Module in it. This uses a RTL8710BN chip.
Now I have 4 plugs laying around who either need the tuya cloud or I can use them as bricks...

**Comment by blakadder** [comment]
You're welcome to submit an edit for that device
