### ISSUE TITLE
SP112 template issue

### ISSUE THREAD

**Issue by JamesT42** [blakadder/templates#1052]
Hi!
Something went wrong with this commit
https://github.com/blakadder/templates/commit/84474ba81da92d87f334e14a0a6f16ad0300258c#diff-ce688f0014cb56cc2f5cf6dbe600721345fb213f0ec6e40195fbffe1f04610ef
The old template works on 9.4.0, the new one has non functioning USB relay and the device resets ~ 1 min after activating the template (I think wrong GPIO for the button? Thus resetting the device)

Also why is only the template für Tasmota 9+ displayed on the website?

Thanks for your awesom work!
Cheers
James

**Comment by blakadder** [comment]
i reverted the commit

because tasmota 9.x is the current version
