### ISSUE TITLE
NEO Coolcam 3in1 Siren new hardware version 1.0.3 flashable with tuya-convert

### ISSUE THREAD

**Issue by vtacquet** [blakadder/templates#1065]
I bought a NEO Coolcam 3in1 and it has a new hardware revision 1.0.3, I was able to flash it with tuya-convert

TYA: MCU Product ID: {"p":"ymf4oruxqx0xlogp","v":"1.0.3","m":0}

**Comment by blakadder** [comment]
thanks, added to the list
