### ISSUE TITLE
Problem with new WiFi Dimmer Switch KingArt

### ISSUE THREAD

**Issue by J3rem** [blakadder/templates#1072]
Hello,
One year ago, I bought two dimmer switch on aliexpress :
[https://fr.aliexpress.com/item/4000160896134.html?aff_fcid=3121dd0fa6e9437ca0429c7e78b97f8b-1622301312779-04718-Ni4UUYli&aff_fsk=Ni4UUYli&aff_platform=link-c-tool&sk=Ni4UUYli&aff_trace_key=3121dd0fa6e9437ca0429c7e78b97f8b-1622301312779-04718-Ni4UUYli&terminal_id=69f41e33ff9d4942b4aa3280104233b1&tmLog=new_Detail](https://fr.aliexpress.com/item/4000160896134.html?aff_fcid=3121dd0fa6e9437ca0429c7e78b97f8b-1622301312779-04718-Ni4UUYli&aff_fsk=Ni4UUYli&aff_platform=link-c-tool&sk=Ni4UUYli&aff_trace_key=3121dd0fa6e9437ca0429c7e78b97f8b-1622301312779-04718-Ni4UUYli&terminal_id=69f41e33ff9d4942b4aa3280104233b1&tmLog=new_Detail)
At that time, I managed to install Tasmota on both dimmers with the following directives :
https://templates.blakadder.com/wifi_dimmer_switch.html
Both dimmers work perfectly, either with the buttons or with Domoticz.
This year, I wanted to buy 10 more to to equip all my outlets but this time it doesn’t work.
Exactly like the last time, I installed Tasmota. Comme la dernière fois, j’ai installé Tasmota à Espeasy.py from the last precompiled version Tasmota-FR.bin available on :
http://ota.tasmota.com/tasmota/
Buttons, Ip commands and domoticz commands don’t work on the lights (ON/OFF, dimmer).
Both cards are alike (see pictures). The only diferenc is the Nuvoton version N76E003AT20 (935gdfa for the old one et 944gdfa for the new one). 
When I sniff, communication between ESP and Nuovoton with Serial Port monitor at 9600 baud,
I get something close to what “digiblur” found in his post (13/09/2018) :
https://www.letscontrolit.com/forum/viewtopic.php?t=5431
I get : 
55 AA 03 07 05 01 01 00 01 01 12 = ON 
55 AA 03 07 05 01 01 00 01 00 11 = OFF
And for example :
55 AA 03 07 08 02 02 04 00 00 03 E8 04 = DIMMER 100
55 AA 03 07 08 02 02 04 00 00 02 EE 09 = DIMMER 75
55 AA 03 07 08 02 02 04 00 00 01 F4 0E = DIMMER 50
55 AA 03 07 08 02 02 04 00 00 00 FA 13 = DIMMER 25
After watching all values, we end up with a stationary base 55 AA 03 07 08 02 02 04 00 00 and three last bytes XX YY ZZ  defining the dimmer values like this :
XX=hex(INT(dimvalue*10 / 256))  for example for DIMMER=100
YY=hex(dimvalue *10 % 256) for example E8 for DIMMER=100
ZZ=hex((dimvalue *10+XX+25) % 256) for example 04 for DIMMER=100
I am a complete newbie in this kind of process... Can you tell me if my procedure is alright ?
Now I’m stuck. I have no idea how to incorporate those informations on Tasmota to solve my problem.
Can it be solved with a simple rule or do I have to change something before it get compiled ? (maybe on file  ps16dz_dimmer.ino ?)
Thank you in advance for every single help you could give me and please excuse my English, I’m French and not quite skilled for foreigner languages.

**Comment by blakadder** [comment]
What you have is a Tuya dimmer... Look at http://tasmota.github.io/docs/TuyaMCU
