### ISSUE TITLE
SP501E - connected LED strip works only 1/3

### ISSUE THREAD

**Issue by Dlay2017** [blakadder/templates#1075]
SP501E - connected LED strip works only 1/3

**Comment by blakadder** [comment]
could you elaborate more than that?

**Comment by Dlay2017** [comment]
No, i cant.
Afterwards i tried to enable WS2812 at rest of the GPIO Ports in Tasmota, but there was no change in the result.

Only 1/3 of the strip worked. Then i found, that no more LEDs light up anymore. Tested v9. 31 of Tasmota Then, same result..

**Comment by blakadder** [comment]
https://tasmota.github.io/docs/Commands/#pixels
