### ISSUE TITLE
Athom Light Swiches

### ISSUE THREAD

**Issue by tungmeister** [blakadder/templates#1094]
@blakadder Hi, do you know if the red and blue LEDs on the Athom light switches  (shown here https://templates.blakadder.com/athom_SW11-TAS-3EU.html) are individually controllable? I'd like to use the switches separately from the relays for controlling smart bulbs - the switches I tried recently couldn't do this.

**Comment by blakadder** [comment]
There are separate LEDs in the template so I'd say: yes

**Comment by tungmeister** [comment]
thanks - I had seen the template but just wanted to make sure. Was it provided by the manufacturer?

**Comment by blakadder** [comment]
yes, i have the clicky version and that one has the same template so you can control led's independently. I actually use one of the keys by mapping the Relay3 to Led3 so it only shows the state of a remote without pointlessly switching the relay

**Comment by tungmeister** [comment]
thanks for that - i'll get an order in!
