### ISSUE TITLE
[Tamplate Issue] Swisstone SH360 GU10 Bulb

### ISSUE THREAD

**Issue by bikejoco** [blakadder/templates#1124]
Hi!
I flashed this Bulb via TuyaConverter without a problem. But when I use these Tamplate:

https://templates.blakadder.com/swisstone_SH360.html

the brightness is reduced. I think that the RGB-LEDs work fine but the ring of the CCT-LEDs won’t work. 

How can I solve this problem?

thank for help 

JOHANNES

**Comment by blakadder** [comment]
swisstone SH 360 is a RGB only bulb

**Comment by bikejoco** [comment]
Ok, but why is the brightness more then 60% reduced after the Flash?

**Comment by blakadder** [comment]
That would be a question for Tasmota support: https://discord.gg/Ks2Kzd4

**Comment by bikejoco** [comment]
Ok, thanks
