### ISSUE TITLE
Bad template athom_PG01EU16A

### ISSUE THREAD

**Issue by ngosang** [blakadder/templates#1125]
File => athom_PG01EU16A
The template does not match the internet references and the pre-flashed template included in the plug.

I just bought this model flashed by manufacturer with
* tasmota 9.1.0
* {"NAME":"Athom Power Monitoring Plug","GPIO":[0,0,0,32,2720,2656,0,0,2624,544,224,0,0,1],"FLAG":0,"BASE":18}

References with template:
* https://www.athom.tech/blank-1/color-smart-plug
* https://www.aliexpress.com/item/4001230982267.html?spm=a2g0s.9042311.0.0.24fc63c0X6sL8g

**Comment by blakadder** [comment]
The template listed on the page is the old format used pre v9. If used on a newer version it will be converted automatically
