### ISSUE TITLE
Mirabella Genio 1002341 plug now being sold with TW-02 (WinnerMicro W600)

### ISSUE THREAD

**Issue by scrad** [blakadder/templates#1128]
I purchased one of these plugs from Coles supermarket today (same parent company owns Kmart in Australia) and was unable to tuya-convert. Pulled it apart to flash via serial and was presented with a completely different (Non esp) board, and therefore unable to flash to tasmota. 

I'm unsure if this is the correct way to go about bringing this up, but as the page mentions nothing about this I believe it's worth mentioning as if there had been some mention of it on the device page I would probably steered clear. 

(FWIW I do have one that I was able to successfully tuya-convert, however that was purchased over 18 months ago. 

Batch Code on the unsupported device is " 2042", while the device that is happily running tasmota is "1943". 

This may help narrow down working and non working devices.

**Comment by blakadder** [comment]
added to the device page, thanks
