### ISSUE TITLE
[Template] Alternative template for KASB10RB22HA Kogan RGBW bulbs

### ISSUE THREAD

**Issue by PanqNZ** [blakadder/templates#1137]
Not sure if the listed template is incorrect of if they've changed the internals at some point, but my KASB10RB22HA bulbs from around 2019 are just four channel PWM and don't have a SM16716 driver at all. Template is:

`{"NAME":"Kogan RGB","GPIO":[0,0,0,0,416,419,0,0,417,0,418,0,0,0],"FLAG":0,"BASE":18}`

**Comment by blakadder** [comment]
added as alternative template. thanks!
