### ISSUE TITLE
[Site Suggestion] - Adding chip_type (ESP32, ESP8266, etc) and chip_flash_size (1Mb, 2Mb,4Mb, etc)

### ISSUE THREAD

**Issue by Phara0h** [blakadder/templates#1155]
I would like to add a suggestion to 2 new enums chip_type and chip_flash_size so people can search for things based on those two params. I ran into this problem when trying to search for RGB bulbs that have at least 4Mb flash. Thanks for your time

**Comment by blakadder** [comment]
i don't have any plans on adding such
