### ISSUE TITLE
Adding sensors

### ISSUE THREAD

**Issue by lsamamig** [blakadder/templates#1158]
Hi there..

I have a aroma diffuser with your template and I´m wondering if it´s possible to add a temperature sensor... but how do I know what pins are there unused? because GPIO01 is (tuya Tx) and GPIO03 is (tuya Rx) but for sure there are others in use, right?

Thanks in advance
[https://templates.blakadder.com/XD80xW.html](url)

**Comment by blakadder** [comment]
any pins not used in the template should be unused

**Comment by lsamamig** [comment]
Wowww that was a very fast answer!!! thank you
