### ISSUE TITLE
New pin layout for Blitzwolf BW-SHP2

### ISSUE THREAD

**Issue by Strixx76** [blakadder/templates#1193]
Opened a Blitzwolf BW-SHP2 which was bought at Banggood in October 2021. Tuya-convert worked, but one OTA went wrong. The following pictures show the pin layout and where to short circuit
![BW-SHP_Serial](https://user-images.githubusercontent.com/17635047/138230317-2894ccb9-6585-40bb-a94d-fb21a5bfa1b9.jpg)
![BW-SHP_IO0-GND](https://user-images.githubusercontent.com/17635047/138230319-7a8c0ea5-280f-40f4-8175-550c7d197b2d.jpg)
.

**Comment by blakadder** [comment]
What is the exact issue with the template here?
