### ISSUE TITLE
B.K. Licht 1253 started shipping new non-tuya-convert-compatible bulbs

### ISSUE THREAD

**Issue by nivek88** [blakadder/templates#1243]
B.K. Licht 1253 started shipping another subversion of their bulbs, which are not compatible with Tuya-convert anymore. Version  BKL1253-BKH101 is capable of tuya-convert. While version BKL1253-BKH168 is not.
![IMG_9087](https://user-images.githubusercontent.com/12642278/143484191-f6f1a2de-8230-4165-990c-ad6d5f4f0bc6.jpeg)

**Comment by blakadder** [comment]
thanks, added to the device page
