### ISSUE TITLE
Deltaco SH-LE27CCTC is not compatible

### ISSUE THREAD

**Issue by blambi** [blakadder/templates#1257]
Similar in appearance to SH-LE27W, minor differences on box it specs Lifetime as 15000h instead of 25000h. And the obvious CCTC instead of W suffix.

I opened it up and it uses ~~UB2L~~ WB2L instead of a ESP8266, so not flashable that way either.

Retailer:
https://www.webhallen.com/se/product/342237-Deltaco-Smart-Home-LED-lampa-E27-WiFi-9W-2700K-6500K-Dimbar-vit

**Comment by blakadder** [comment]
Did you mean WB2L?

**Comment by blambi** [comment]
Yes, meant to say WB2L.
