### ISSUE TITLE
[Template issue] Gosund SW9 Buttons and Leds

### ISSUE THREAD

**Issue by smart4h** [blakadder/templates#1269]
GosundSW9 template is not working for me. My solution is as follows:
Switches should be swapped with buttons and relay state red leds are related with GPIO2 (Relay1) and GPIO4 (Relay2), Connection status can be indicaned with green  LedLink_i on GPIO13.

`{"NAME":"GosundSW9","GPIO":[32,0,288,0,289,33,0,0,225,576,224,0,0,0],"FLAG":0,"BASE":18}`

![image](https://user-images.githubusercontent.com/56863939/145101468-02101759-170a-4811-84a1-238698cc8c43.png)

**Comment by blakadder** [comment]
that does make more sense
