### ISSUE TITLE
Tuya curtain motor need help

### ISSUE THREAD

**Issue by hoangtruong2412** [blakadder/templates#1273]
Hello! i have a Tuya curtain motor, i loaded tasmota for esp chip, then i configured the module as Tuyamcu, and i don't know what to do next to make the motor spin, and how to put it to home assistant? please help me. thanks a lot

**Comment by hoangtruong2412** [comment]
please tell me, why close my topic?

[image: image.png]


Vào Th 6, 10 thg 12, 2021 vào lúc 18:07 blakadder <
***@***.***> đã viết:

**Comment by blakadder** [comment]
![image](https://user-images.githubusercontent.com/5904370/145590712-3c7789a4-e415-4b52-9cfe-1153a631da44.png)

**Comment by hoangtruong2412** [comment]
Hello! I edited the post, added product images, and some things I did,
please reopen the topic and help me, many thanks!

[image: image.png]


Vào Th 6, 10 thg 12, 2021 vào lúc 21:36 blakadder <
***@***.***> đã viết:
