### ISSUE TITLE
The current AVATTO 3-way v4.1 switches are no longer with a TYWE3S module but with a WB3S

### ISSUE THREAD

**Issue by octavius08** [blakadder/templates#1279]
For support with Tasmota flashing and configuring the device visit [Tasmota Discord](https://discord.gg/Ks2Kzd4).
For support with Tuya-Convert please use their [GitHub Issues](https://github.com/ct-Open-Source/tuya-convert/issues).

Hello Comunity 
I recently bought an AVATTO 3-way switch, as it turned out, they are no longer delivered with an ESP8266 chip. 
And here is my solution after 6 hours of work :)

The current AVATTO 3-way v4.1 switches are no longer with a TYWE3S module but with a WB3S module. 
![AVATTO_3W_v1 4](https://user-images.githubusercontent.com/61793794/145787163-cbf83b85-23e0-4ccd-b9bc-f7c13df6277a.jpg)

![WB3S](https://user-images.githubusercontent.com/61793794/145786191-c0dcdde3-16ba-47ef-ae64-a72aa4aaa373.jpg)

However, it is possible to change the WB3S module for an ESP2866 12F. This procedure is time-consuming and need some modifications on the board:
![PIC_01](https://user-images.githubusercontent.com/61793794/145784697-79ebfc00-6dad-4fd6-8c53-3facb358e3d7.jpg)
![PIC_02](https://user-images.githubusercontent.com/61793794/145784716-a6e56a7a-9ac7-4f16-9a23-4c6d4e351309.jpg)

The old template works no longer either, here the working template for v4.1 AVATTO 3 Way:
{"NAME":"AVATTO 3 Gang v4.1","GPIO":[0,226,544,34,32,33,0,0,288,224,289,225,290,0],"FLAG":0,"BASE":18}

Best regards and excuse my english :)

**Comment by blakadder** [comment]
Using ESP-12S or ESP-12H will remove the need for the additional resistor

**Comment by octavius08** [comment]
> Using ESP-12S or ESP-12H will remove the need for the additional resistor

Thanks, I didn't know that, I only had the 12F there. 
Finally I solder a SMD 10k resistor directly to the board inbetween GPIO15 and GND
