### ISSUE TITLE
Lumary L-DS100 with ESP-12S. Need help.

### ISSUE THREAD

**Issue by rezon8** [blakadder/templates#1294]
I'm a newbie when it come to Tasmota, so I'm still trying to figure out some things. I bought this Lumary DS100 dimmer before getting into Tasmota and found out later that it isn't readily compatible. I have a couple other switches from a different vendor that flashed easily and are working properly. With this Lumary dimmer, the Tasmota site says that it should be compatible if you swap out the module, so that's what I did. I popped in an ESP-12S after flashing it via a development board. I then installed the dimmer switch in the wall and it works properly when I physically click on it and I can access the Tasmota web GUI to configure and flash/update the dimmer, however, I can't seem to get it to respond to the toggle/power command to actually turn it on or off via the web interface or remotely otherwise. Can anyone help me to troubleshoot this and confirm what the configuration / GPIOs should be?

**Comment by blakadder** [comment]
![](https://user-images.githubusercontent.com/5904370/145590712-3c7789a4-e415-4b52-9cfe-1153a631da44.png)

[https://tasmota.github.io/docs/](https://tasmota.github.io/docs/)
