### ISSUE TITLE
Sonoff M5 does not fit in EU mounting box[Site issue]

### ISSUE THREAD

**Issue by tremichl** [blakadder/templates#1341]
For support with Tasmota flashing and configuring the device visit [Tasmota Discord](https://discord.gg/Ks2Kzd4).
For support with Tuya-Convert please use their [GitHub Issues](https://github.com/ct-Open-Source/tuya-convert/issues).

![M5 diameter](https://user-images.githubusercontent.com/22281548/152552102-0f49e7c8-6d1c-4b59-8858-45e447662228.jpg)

DIN49073 EU mounting box has 60mm mounting opening!
![IMG_20220203_121852](https://user-images.githubusercontent.com/22281548/152552412-f2224e16-1792-4955-a799-938536dc7179.jpg)

**Comment by blakadder** [comment]
And others have a 63mm opening
