### ISSUE TITLE
DP-WP001 is coming with the XR3/XR809 chip

### ISSUE THREAD

**Issue by carlos-algms** [blakadder/templates#1348]
Should we update the docs? Or maybe move it to the "unsupported" section?

I bought it from Aliexpress in May/2021. 
https://www.aliexpress.com/item/1005001977463358.html?spm=a2g0o.9042311.0.0.27424c4dcvr4eT

The manufacturing date seems to be `2021-01-15` 

[DP-WP001 template](https://github.com/blakadder/templates/blob/master/_templates/DP-WP001)

![image](https://user-images.githubusercontent.com/4634613/154555140-3963d31b-0e2c-4acb-adeb-a32ff3686ee7.png)

![image](https://user-images.githubusercontent.com/4634613/154555265-35c6a0d8-778e-4170-a335-c18314ea6b70.png)

![image](https://user-images.githubusercontent.com/4634613/154555437-30b35bd5-2040-4b02-a1c0-c045cb2b3d94.png)

**Comment by blakadder** [comment]
updated
