### ISSUE TITLE
template_alt not shown on actual page

### ISSUE THREAD

**Issue by soxhi8** [blakadder/templates#1351]
So maybe I am blind, but template_alt only exists in code and is not displayed on the actual wiki.
Example (non-critical, just to illustrate the issue):
https://templates.blakadder.com/gosund_SP112_v3_4.html
https://github.com/blakadder/templates/blob/master/_templates/gosund_SP112_v3_4

Is this intentional?

**Comment by blakadder** [comment]
fixed
