### ISSUE TITLE
owfeel_EN71 - Led and Relay are inverted - subtle

### ISSUE THREAD

**Issue by wipeout666** [blakadder/templates#1411]
GPIO00 Relay1 and GPIO13 are inverted. The device will work properly even if inverted, since the LED always have the same state as the relay. HOWEVER, this is not true when wifi is connecting; the LED will flash. Therefore, the template, as posted, will have the valve toggle between open and close with a 1 second period. This could eventually burn the gearbox if wifi is down for a signification amount of time.

Tested on my valve.

![image](https://user-images.githubusercontent.com/71163149/166618206-414bb431-4d80-47e9-87b9-73a02b9313be.png)

**Comment by blakadder** [comment]
corrected

**Comment by mrmaximas** [comment]
@wipeout666 may be you have original tuya fw backup for this valve? thanks!

**Comment by wipeout666** [comment]
No I don't, sorry
