### ISSUE TITLE
Aoycocr EU5-16A Plug - No Power Monitoring

### ISSUE THREAD

**Issue by smoldersonline** [blakadder/templates#144]
I've installed this template on this plug. Power toggle works fine, but unfortunately no power monitoring.

Edit: product information on Amazon(.de) is incorrect. This plug has no power monitoring.

**Comment by blakadder** [comment]
The template doesn't even have power monitoring gpio's assigned so I don't see what your issue was

**Comment by smoldersonline** [comment]
I sincerely apologise. The plug is (incorrectly) advertised by Amazon(.de) as a plug with power monitoring. On this basis I was expecting this functionality.

I returned the plugs.
