### ISSUE TITLE
Update template for AUKEY SH-PA1

### ISSUE THREAD

**Issue by dark-nova** [blakadder/templates#145]
Hi,

I was the user who submitted the template for the [SH-PA1](https://github.com/blakadder/templates/blob/master/_templates/aukey_SH-PA1). I discovered the correct input for the pin for LED control. Here is an updated template:

`{"NAME":"AUKEY SH-PA1","GPIO":[0,0,57,0,0,0,0,0,0,17,0,21,0],"FLAG":15,"BASE":18}`

**Comment by blakadder** [comment]
Thanks
