### ISSUE TITLE
Teckin SP23 Power LED - incorrect template

### ISSUE THREAD

**Issue by msp1974** [blakadder/templates#150]
Hi,

Used your template info to config Tasmota for my new SP23s.  Works a treat, except the led on the button does not show the power status.  This is because the template should be like below (ie 2 led settings swapped).  Perhaps you could update for others who find same issue.

{"NAME":"Teckin SP23","GPIO":[56,255,57,255,0,134,0,0,131,17,132,21,0],"FLAG":0,"BASE":45}

KR

**Comment by blakadder** [comment]
Corrected
