### ISSUE TITLE
TGWF115PQM: Different chip entirely

### ISSUE THREAD

**Issue by luke-jr** [blakadder/templates#1514]
Topgreener replaced TGWF115PQM with new insides, completely different chip :(

**Comment by blakadder** [comment]
which chip is it?

**Comment by luke-jr** [comment]
BK7231N CU1074DC

https://fccid.io/2A2KT-WF10FPM-1/Internal-Photos/09-SK566-WP-IntPho-5357615

https://www.amazon.com/gp/customer-reviews/R2SCAW67Z3KLQE/ref=cm_cr_arp_d_rvw_ttl?ie=UTF8&ASIN=B07D8ZNNPZ
