### ISSUE TITLE
Tessan STD02 - syntax error in template cmnd

### ISSUE THREAD

**Issue by brewtangclan** [blakadder/templates#1529]
https://templates.blakadder.com/tessan_STD02.html

Page lists the template as `{"NAME":"Tessan-STD02","GPIO":[0,2272,0,2304,0,0,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":54,"CMND":"SO97 | TuyaMCU 11,1 | TuyaMCU 21,2 | DimmerRange 20,255"}` (Note the SO97 without a value). 

Should be `{"NAME":"Tessan-STD02","GPIO":[0,2272,0,2304,0,0,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":54,"CMND":"SO97 1 | TuyaMCU 11,1 | TuyaMCU 21,2 | DimmerRange 20,255"}`

With the corrected template the main page of the Tasmota web interface shows the dimmer slider. With the template as listed on the page, the DimmerRange command doesn't get processed and the dimmer slider is not shown.

**Comment by blakadder** [comment]
fixed
