### ISSUE TITLE
Question AWP08l Template

### ISSUE THREAD

**Issue by mobidarabbit** [blakadder/templates#153]
Hello,
what is the Analog0 parameter in the template AWP08l for?

With regards,
Martin

**Comment by blakadder** [comment]
Its an old template, its probably a remnant from when you could read voltage on the PCB if yo udon't have anything connected to the analog pin of the esp8266

**Comment by blakadder** [comment]
let me know if changing the flag to 0 fixes it!

**Comment by mobidarabbit** [comment]
Changing the flag to 0 is the answer. Thank you!
