### ISSUE TITLE
Gosund SW9 - tuya-convert not available

### ISSUE THREAD

**Issue by nowayitsgoingtowork** [blakadder/templates#1619]
Accoriding to info at [SW9 page](https://templates.blakadder.com/gosund_SW9.html) I've contacted Gosund (globalservice@gosund.com) and they are very responsive. Unfortunately the only device they can help to install Tamota with Tuya Convert is EP2 and not SW9. They replied that SW9 isn't visible to their system. Flashing with serial pins worked flawlessly though.

**Comment by blakadder** [comment]
thanks for reporting
