### ISSUE TITLE
powertech_MS6106 GPIO13 mode

### ISSUE THREAD

**Issue by samjwass** [blakadder/templates#1638]
Hey blakadder, much thanks for the templates. I've found an issue with the Jaycar MS6106 in case anyone else comes across it.
GPIO13 needs to be set as a Button, not a Switch.
When configured as a Switch the hardware button does not toggle power, the relay is only engaged so long as the button is held. This means the socket cannot be used standalone.
After changing it to a Button, the relay is toggled on/off at each button press as per factory.

**Comment by blakadder** [comment]
You just had to change Switchmode for that switch
