### ISSUE TITLE
DIYMORESOILDHT11 template

### ISSUE THREAD

**Issue by ploeffler** [blakadder/templates#1659]
...generates 
Analog1 Range
and 
Analog2 Range

which is which - showing no reasonable data

**Comment by blakadder** [comment]
can you elaborate your stream of thought?

**Comment by ploeffler** [comment]
hi @blakadder, sorry for the long delay
(I destroyed my device with overvoltage and had to wait for a new one)

ok, I activated the template as suggested and there are definitions for 2 analog-inputs, one on GPIO32 and the other one on GPIO34

my question(s) now is/are:

at which GPIO is the capacitive sensor?
and
what is the second ADC doing?

hope that makes it more clear

regards
peter

**Comment by blakadder** [comment]
I wouldn't know because I do not own the device

**Comment by ploeffler** [comment]
:(
oh, I thought thats your template definitions -sorry

**Comment by ploeffler** [comment]
update: the soilsensor is on GPIO32, GPIO34 is not connected
