### ISSUE TITLE
[Site issue] Template (requires valid JSON template) ==> Not a valid template!

### ISSUE THREAD

**Issue by lboue** [blakadder/templates#1737]
# Error
I would like to propose a new addition but the validation of the replace indicates an error to me while my template is valid.
`Template (requires valid JSON template)
`
### Reproduce step

Copy this template to this form: https://templates.blakadder.com/new.html
```
{"NAME":"M5Stamp S3","GPIO":[32,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,1,1,1,1376,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1],"FLAG":0,"BASE":1}
```

### Result
Error:
`Template (requires valid JSON template)
`

**Comment by blakadder** [comment]
fixed
