### ISSUE TITLE
Earu RDCBC-1P 63A nov2023 eWeLink version 

### ISSUE THREAD

**Issue by rafaeldelgadoc** [blakadder/templates#1822]
This device, on version eWeLink (november 2023), have PSF-B01 no Tuya MCU. PSF-B01 is a single-channel ultra-low-power Wi-Fi switch module based on ESP8285. It can flash with Tasmota USB serial TTL. (https://templates.blakadder.com/PSF-B.html)
The template for this is:
{"NAME":"RDCBC-1P","GPIO":[32,0,0,0,0,0,0,0,288,224,0,0,0,0],"FLAG":0,"BASE":18}

**Comment by blakadder** [comment]
There's a Submit new template option for this
