### ISSUE TITLE
Site images #2

### ISSUE THREAD

**Issue by blakadder** [blakadder/templates#19]
.
![image](https://user-images.githubusercontent.com/5904370/67624505-af524080-f831-11e9-9c2c-64fdf7af1868.png)

![image](https://user-images.githubusercontent.com/5904370/55722006-390cfe80-5a05-11e9-86e5-9069dfc7336b.png)
![image](https://user-images.githubusercontent.com/5904370/55916503-ce1e1c00-5bec-11e9-96c7-7eff83b0951c.png)
![image](https://user-images.githubusercontent.com/5904370/55916577-0160ab00-5bed-11e9-8e9b-c20bf489af07.png)
![image](https://user-images.githubusercontent.com/5904370/56020785-3c0b3600-5d08-11e9-82e2-9bf0ee24169e.png)
![image](https://user-images.githubusercontent.com/5904370/56110927-779b3f80-5f56-11e9-92f2-8b6993b8b1d9.png)
![image](https://user-images.githubusercontent.com/5904370/56112013-0c536c80-5f5a-11e9-86fe-8688ad21f8c6.png)
![image](https://user-images.githubusercontent.com/5904370/56112085-4c1a5400-5f5a-11e9-8c6a-1fce0f36f146.png)
![image](https://user-images.githubusercontent.com/5904370/56116577-7b36c280-5f66-11e9-9052-f97a35669708.png)
![image](https://user-images.githubusercontent.com/5904370/56267544-65a0d480-60ef-11e9-97f8-126c4053ae9e.png)
![image](https://user-images.githubusercontent.com/5904370/56273527-2c6f6100-60fd-11e9-8c4d-faa16971f7da.png)
![image](https://user-images.githubusercontent.com/5904370/56273950-1a41f280-60fe-11e9-8b2f-8fc8a1ab77e9.png)
![image](https://user-images.githubusercontent.com/5904370/56278781-254d5080-6107-11e9-90b4-a68579147e74.png)
![image](https://user-images.githubusercontent.com/5904370/56278820-3bf3a780-6107-11e9-9f53-eb3c198dffff.png)

![image](https://user-images.githubusercontent.com/5904370/56409876-446cef00-627b-11e9-8a12-9a0ed4ef6ee6.png)
![image](https://user-images.githubusercontent.com/5904370/56752390-6fc67100-6788-11e9-926b-8afd519cef61.png)
![image](https://user-images.githubusercontent.com/5904370/57200999-010cc300-6f93-11e9-8fbe-ad02435e367f.png)
![image](https://user-images.githubusercontent.com/5904370/57507574-7e239980-72ff-11e9-9694-bbda10740451.png)
![image](https://user-images.githubusercontent.com/5904370/57791754-c0087180-773d-11e9-845a-afcfa926bf49.png)
![image](https://user-images.githubusercontent.com/5904370/57791840-f8a84b00-773d-11e9-824b-55aee1468235.png)
![image](https://user-images.githubusercontent.com/5904370/58085795-b3609f00-7bbd-11e9-800b-88a9ec1a43cb.png)
![image](https://user-images.githubusercontent.com/5904370/58165226-a4462380-7c87-11e9-854e-e3fdbf7b345d.png)
![image](https://user-images.githubusercontent.com/5904370/58311134-94098200-7e08-11e9-846d-1bf06b2cac02.png)

![image](https://user-images.githubusercontent.com/5904370/61628399-7890eb00-ac82-11e9-9742-3e837ee9f09b.png)
![image](https://user-images.githubusercontent.com/5904370/63218034-97837f80-c151-11e9-8a83-c908a7308143.png)
![image](https://user-images.githubusercontent.com/5904370/63218053-137dc780-c152-11e9-8190-10709858a97d.png)
![image](https://user-images.githubusercontent.com/5904370/63218065-59d32680-c152-11e9-8574-de7ff865743f.png)
![image](https://user-images.githubusercontent.com/5904370/63218083-cbab7000-c152-11e9-84e7-29edf0da090a.png)
![image](https://user-images.githubusercontent.com/5904370/63218096-702db200-c153-11e9-99b5-3fb240286543.png)
![image](https://user-images.githubusercontent.com/5904370/63218102-9eab8d00-c153-11e9-85d7-4dd2fee332cd.png
![image](https://user-images.githubusercontent.com/5904370/63218113-006bf700-c154-11e9-8d0f-6a49f9409451.png)
![image](https://user-images.githubusercontent.com/5904370/63218166-66a54980-c155-11e9-90ef-189c56e0ae0f.png)
![image](https://user-images.githubusercontent.com/5904370/64081455-6f734f00-cd01-11e9-95cd-b556c776e6d3.png)
![image](https://user-images.githubusercontent.com/5904370/65447568-23ff1d00-de37-11e9-8c18-c4bb24372194.png)
![image](https://user-images.githubusercontent.com/5904370/65717055-b9511a00-e0a0-11e9-9e7d-2623af6cbcac.png)
![image](https://user-images.githubusercontent.com/5904370/66565694-60cf5180-eb63-11e9-98c4-91ee43d142d8.png)
![image](https://user-images.githubusercontent.com/5904370/66715385-0a604e00-edc3-11e9-8aa9-7e93eaa6c115.png)
![image](https://user-images.githubusercontent.com/5904370/66715410-5c08d880-edc3-11e9-96e0-6a37854058d1.png)
![image](https://user-images.githubusercontent.com/5904370/66715805-e8b59580-edc7-11e9-954e-dfd45c1fc07e.png)
![image](https://user-images.githubusercontent.com/5904370/66716276-fc62fb00-edcb-11e9-85e1-dd441e439c64.png)
![image](https://user-images.githubusercontent.com/5904370/66717077-5b793d80-edd5-11e9-8e10-13065610b1d3.png)
![image](https://user-images.githubusercontent.com/5904370/66717093-86639180-edd5-11e9-900b-724da9c89916.png)
![image](https://user-images.githubusercontent.com/5904370/66717120-e1958400-edd5-11e9-931c-abc59f86ed3d.png)
![image](https://user-images.githubusercontent.com/5904370/66717175-536dcd80-edd6-11e9-8e3e-da3e76cc3e43.png)
![image](https://user-images.githubusercontent.com/5904370/66717187-7d26f480-edd6-11e9-996a-ee2f3f86e3c0.png)
![image](https://user-images.githubusercontent.com/5904370/66717288-8d8b9f00-edd7-11e9-9bc9-b0bd31b13545.png)
![image](https://user-images.githubusercontent.com/5904370/66717348-46ea7480-edd8-11e9-8a97-ed77cc93cb7a.png)
![image](https://user-images.githubusercontent.com/5904370/66717408-fb849600-edd8-11e9-834e-3eb4a1b994d8.png)
![image](https://user-images.githubusercontent.com/5904370/66717435-47cfd600-edd9-11e9-9406-7059bc04e2a9.png)
![image](https://user-images.githubusercontent.com/5904370/66717441-5e762d00-edd9-11e9-9b65-27adea758d65.png)
![image](https://user-images.githubusercontent.com/5904370/66717458-967d7000-edd9-11e9-9952-eb163b595bba.png)
![image](https://user-images.githubusercontent.com/5904370/66717473-b745c580-edd9-11e9-9dc3-96dafab812c6.png)
![image](https://user-images.githubusercontent.com/5904370/66717540-8fa32d00-edda-11e9-8f99-b1948457fbf6.png)
![image](https://user-images.githubusercontent.com/5904370/66717605-1fe17200-eddb-11e9-9c76-3bb3ccc9a9b0.png)
![image](https://user-images.githubusercontent.com/5904370/66717637-777fdd80-eddb-11e9-8764-04d1158a329b.png)
![image](https://user-images.githubusercontent.com/5904370/66717664-c3328700-eddb-11e9-97aa-fb8366ae4953.png)
![image](https://user-images.githubusercontent.com/5904370/66717679-0e4c9a00-eddc-11e9-8db4-a2bca9fa0791.png)
![image](https://user-images.githubusercontent.com/5904370/66717700-49e76400-eddc-11e9-87f4-2e3b2667eac0.png)
![image](https://user-images.githubusercontent.com/5904370/66717715-697e8c80-eddc-11e9-8cce-d925f78d2f1b.png)
![image](https://user-images.githubusercontent.com/5904370/66717744-bb271700-eddc-11e9-9bcf-d6f53437d201.png)
![image](https://user-images.githubusercontent.com/5904370/66717793-502a1000-eddd-11e9-9b38-1295260c3854.png)
![image](https://user-images.githubusercontent.com/5904370/66717839-bf076900-eddd-11e9-8e07-154377d87dcd.png)
![image](https://user-images.githubusercontent.com/5904370/66717877-1e657900-edde-11e9-97a6-ae426b60bc1f.png)
![image](https://user-images.githubusercontent.com/5904370/66717934-697f8c00-edde-11e9-8a0b-36f9c5d9a5a5.png)
![image](https://user-images.githubusercontent.com/5904370/66717949-9fbd0b80-edde-11e9-8dd0-36e09e7a7114.png)
![image](https://user-images.githubusercontent.com/5904370/66718127-ab113680-ede0-11e9-945b-c717cf56ab04.png)
![image](https://user-images.githubusercontent.com/5904370/66718142-d4ca5d80-ede0-11e9-909a-77bd4f315909.png)
![image](https://user-images.githubusercontent.com/5904370/66718161-080cec80-ede1-11e9-94f3-7cf3ea739bb3.png)
![image](https://user-images.githubusercontent.com/5904370/66718388-9d10e500-ede3-11e9-95b5-2c7c58f1572e.png)
![image](https://user-images.githubusercontent.com/5904370/66718462-8919b300-ede4-11e9-9324-ca4ee0267c19.png)
![image](https://user-images.githubusercontent.com/5904370/66718486-cf6f1200-ede4-11e9-89c5-acaf2280879e.png)
![image](https://user-images.githubusercontent.com/5904370/66718514-1c52e880-ede5-11e9-8334-4644c016fc42.png)
![image](https://user-images.githubusercontent.com/5904370/66718533-43111f00-ede5-11e9-8cb4-52b2f0c64263.png)
![image](https://user-images.githubusercontent.com/5904370/66906978-df673b80-f008-11e9-8997-eba70d868af1.png)
![image](https://user-images.githubusercontent.com/5904370/66994022-e6f01880-f0cc-11e9-906d-d5861885d3d9.png)
![image](https://user-images.githubusercontent.com/5904370/67141285-f05eb980-f261-11e9-97e8-72ab86e779ac.png)
![image](https://user-images.githubusercontent.com/5904370/67141457-2865fc80-f262-11e9-9388-8435ab922410.png)
![image](https://user-images.githubusercontent.com/5904370/67286319-7c2e4b00-f4d9-11e9-9c3d-993e5a8c6422.png)
![image](https://user-images.githubusercontent.com/5904370/67376889-231bf100-f585-11e9-95f2-f7e841804439.png)
![image](https://user-images.githubusercontent.com/5904370/67377332-c8cf6000-f585-11e9-9de7-e7ce43a277d9.png)
![image](https://user-images.githubusercontent.com/5904370/67437127-68c1d380-f5f0-11e9-91e6-4d307da269fa.png)

**Comment by digiblur** [comment]
![lohas_e26](https://user-images.githubusercontent.com/3240875/67115086-ff326700-f1a2-11e9-86ac-9d2b3a6a7f86.jpg)

**Comment by digiblur** [comment]
![anoop_cw_ww](https://user-images.githubusercontent.com/3240875/67770831-24d23280-fa25-11e9-9043-348c90a6ffe3.jpg)
![aoycocr](https://user-images.githubusercontent.com/3240875/67770845-2ac81380-fa25-11e9-9dc2-4dc46bbdd48b.jpg)

**Comment by digiblur** [comment]
Blitzwolf Light Strip 
![blitzwolf_led_strip](https://user-images.githubusercontent.com/3240875/67770865-34ea1200-fa25-11e9-8f19-4f00216ca669.jpg)

**Comment by digiblur** [comment]
Esicoo Plug

![Esicoo](https://user-images.githubusercontent.com/3240875/67770887-3fa4a700-fa25-11e9-99d7-bf8b59deb363.jpg)

**Comment by digiblur** [comment]
Esicoo Bulb 

![esicoo_bulb](https://user-images.githubusercontent.com/3240875/67770912-4af7d280-fa25-11e9-82b7-97947c779224.JPG)

KS811 Dual 

![ks811_dual](https://user-images.githubusercontent.com/3240875/67770927-50edb380-fa25-11e9-9b53-26186d621b4b.JPG)

KS7011 Dimmer

![ks7011_dimmer](https://user-images.githubusercontent.com/3240875/67770937-56e39480-fa25-11e9-9531-596e985b9119.JPG)

Kuled Switch

![kuled_switch](https://user-images.githubusercontent.com/3240875/67770948-5c40df00-fa25-11e9-9aba-f6f6dcabb14e.JPG)

**Comment by digiblur** [comment]
Martin Jerry Switch 
![MJSwitch2](https://user-images.githubusercontent.com/3240875/67770968-64991a00-fa25-11e9-8a79-deed6e0b5373.jpg)

Moes 3 Way 

![moes3way](https://user-images.githubusercontent.com/3240875/67770976-695dce00-fa25-11e9-9b82-ae12b04f6e7d.JPG)

**Comment by digiblur** [comment]
Oukitel P1 Plug 

![OukitelP1](https://user-images.githubusercontent.com/3240875/67770988-724e9f80-fa25-11e9-9fdd-47576ee8a35e.JPG)

**Comment by digiblur** [comment]
Reafoo Bulb

![reafoo](https://user-images.githubusercontent.com/3240875/67771019-7bd80780-fa25-11e9-90a9-fd89dd78325c.jpg)

S118-01K1

![ss118-01k1_switch](https://user-images.githubusercontent.com/3240875/67771038-82667f00-fa25-11e9-8463-baf7de7d1f3e.jpg)

TWE3S Pins 
![tywe3s_pins](https://user-images.githubusercontent.com/3240875/67771060-8befe700-fa25-11e9-87cd-72ccb8805a72.png)
