### ISSUE TITLE
BlitzWolf BW-SHP7 Current Problem

### ISSUE THREAD

**Issue by GeforceGamer** [blakadder/templates#190]
Hello,
I have an BlitzWolf SHP7 Device with Tasmota 6.7.1 and used the template from here. But the current sensor doesn't work right. With no calibration the current is by over 16A with an 40W bulb and an voltage of 229V. After calibration the current is right, but only for this bulb. If I use an devices with more than 40W the current doesn't show the right value. I don't know if there is something wrong with the template or with my plug.

**Comment by blakadder** [comment]
could be either. templates are submitted by other users and there could be issues
