### ISSUE TITLE
550ml diffuser not homekit compatible (fan component)

### ISSUE THREAD

**Issue by daaf84** [blakadder/templates#191]
https://www.home-assistant.io/integrations/homekit/ says:
>  The first entry of speed_list should be equivalent to off to match HomeKit’s concept of fan speeds. 

This one is missing "off", Ive tried different solutions, but Homekit keeps trowing errors about missing the off state.

**Comment by blakadder** [comment]
this is not meant to work with homekit since its a hacky implementation and it has separate commands for power on/off and fan speeds
