### ISSUE TITLE
Template for AOFO 4AC+4USB not working

### ISSUE THREAD

**Issue by realex-me** [blakadder/templates#197]
Hey blakaddr,
A few days ago I bought the new Smart Power Strip „AOFO 4AC+4USB “ on Amazon. Yesterday I flashed it with Sonoff-Tasmota 6.7.1 by Theo Arends and configured it with your template but as result i got only one Toggle Button which toggles the state of Plug 1 (see image below). Are there any additional configurations I have to do?

<img width="370" alt="Bildschirmfoto 2019-11-23 um 08 03 56" src="https://user-images.githubusercontent.com/58101950/69474998-dddb2100-0dc7-11ea-9f76-5d5319836f99.png">

**Comment by blakadder** [comment]
There are a few power strips named that. Maybe you have a different version or your template isn't applied correctly

**Comment by blakadder** [comment]
Another version of the template added
