### ISSUE TITLE
Template for jinvoo_SM-PW713 not working

### ISSUE THREAD

**Issue by schrej-zz** [blakadder/templates#199]
When using this template, the valve resets and goes back into wifiman mode (192.168.4.1).
Sonoff Basic template is working, at least the valve. Did not check the LEDs yet.

**Comment by blakadder** [comment]
probably the button registers as on and activates the reset to defaults feature after 40 seconds. try inverting the button and see if that helps

**Comment by blakadder** [comment]
There's a V2 version of the template added
