### ISSUE TITLE
H801 template does not have white channel

### ISSUE THREAD

**Issue by robin13** [blakadder/templates#216]
When applying the h801 [template](https://blakadder.github.io/templates/h801.html), the web interface (and reported auto-config) does not seem to contain a channel for switching the Warm-White LEDs:

![screenshot-2019-12-02_10-40-46](https://user-images.githubusercontent.com/174291/69948681-593b8180-14f0-11ea-99df-029d1d8a4f45.png)

**Comment by robin13** [comment]
Tasmota 6.7.1 BTW and the white light is connected to W1

**Comment by blakadder** [comment]
Thanks. I'll check and update once I get access to my H801

**Comment by robin13** [comment]
Having updated to 7.1.1 I now see:

![screenshot-2019-12-02_16-42-21](https://user-images.githubusercontent.com/174291/70038223-35dc0980-15b8-11ea-83b2-8a5595fffd72.png)

So actually now all of the elements are visible, BUT when I change the warm/cool slider, the coloured LEDs go out, and when I change the colour selector slider the white LEDs go out.. it seems as if each command automatically turns off the "other" ... so I'm not sure if this is a template issue, or a limitation of tasmota?

**Comment by blakadder** [comment]
you can control either rgb or white channel with sliders
