### ISSUE TITLE
To  @meingraham

### ISSUE THREAD

**Issue by frablaser** [blakadder/templates#219]
Hi Mr @meingraham

In the templates I saw the DS01 US dimmer, the new release of this dimmer is no more what is shown in the picture. The hardware really changed, it is not possible to soldering the wires directly to the ESP microcontroler anymore. It is to tiny and the PCB donuts are became very tiny also (less than 1.5 mm) with a big welding nose it could cause some big damages.

In the board, there is some holes and plates where you can soldering your wires, but it is near the double of a hair size may be.
I tried to flash it, but it seems the the GPO0 isn't at the same place (put it to the GND don't affect the ESP boot) and I can't figure out how to set the ESP to be flashed... I tried with or without the flat wires plugged.  

Pictures:
![20191202_222753](https://user-images.githubusercontent.com/29067539/70021858-1ca76e80-1560-11ea-8096-49094db75c14.jpg)
![20191202_224802](https://user-images.githubusercontent.com/29067539/70021859-1ca76e80-1560-11ea-83eb-3697603325ac.jpg)
![20191202_225210](https://user-images.githubusercontent.com/29067539/70021860-1d400500-1560-11ea-90e5-23ce806a3368.jpg)
![20191202_225529](https://user-images.githubusercontent.com/29067539/70021861-1d400500-1560-11ea-96db-1d48231dbea9.jpg)
![20191202_220639](https://user-images.githubusercontent.com/29067539/70021862-1dd89b80-1560-11ea-8ec0-93d889121c1c.jpg)
![20191202_220932](https://user-images.githubusercontent.com/29067539/70021864-1dd89b80-1560-11ea-9494-f522427e4aa8.jpg)
![20191202_220943](https://user-images.githubusercontent.com/29067539/70021865-1dd89b80-1560-11ea-8ba2-af3cc6c1eaf2.jpg)
![20191202_222725](https://user-images.githubusercontent.com/29067539/70021866-1dd89b80-1560-11ea-93c4-79162874fb08.jpg)
![20191202_222741](https://user-images.githubusercontent.com/29067539/70021867-1dd89b80-1560-11ea-9a49-2277743c5e94.jpg)

**Comment by meingraham** [comment]
Did you try Tuya-Convert on this device?

This may be a case where the RST pin on the secondary MCU is keeping the ESP chip from going into boot mode. This has been reported for other Tuya devices with a secondary MCU. 

https://github.com/arendst/Tasmota/wiki/MCU-Based-Tuya-Dimmers-and-Switches#flashing---preparation

I don't have any other suggestions.

**Comment by blakadder** [comment]
Definitely not a site issue.

**Comment by frablaser** [comment]
@blakadder Yes not a site issue at all...  But No other way for me to contact Mr Ingraham... 😌

@meingraham 
I converted a lot of devices, but this one resist...

I will try to figure out the RST pin on the secondary MCU. Do you think I could remove the soldering on the RST on the master MCU?

**Comment by meingraham** [comment]
> No other way for me to contact Mr Ingraham

Tasmota Discord - https://discord.gg/Ks2Kzd4
