### ISSUE TITLE
[Site issue] Oittm Smart Plug Broken

### ISSUE THREAD

**Issue by fortepc** [blakadder/templates#250]
For support with Tasmota flashing and configuring the device visit [Tasmota Discord](https://discord.gg/Ks2Kzd4).
For support with Tuya-Convert please use their [GitHub Issues](https://github.com/ct-Open-Source/tuya-convert/issues).

https://blakadder.github.io/templates/oittm_plug.html

None of the "Available From" links work on this page.

**Comment by blakadder** [comment]
Then they're removed by the maker/seller which means the plug is probably not being distributed anymore
