### ISSUE TITLE
GPIO and AC warning

### ISSUE THREAD

**Issue by allistermaguire** [blakadder/templates#26]
I didn't think about it at the time but it should probably have a warning on the page regarding serial connectivity while AC is connected. Something like this:

## :warning: Electrocution Risk :warning:

**Do not connect AC power and the serial connection at the same time** 
The GND connection of Shelly devices is connected to the live AC wire. Connecting serial with your PC will fry your PC and could electrocute you.

**Do not connect any additional sensors to serial pins.**

**Comment by blakadder** [comment]
will do
