### ISSUE TITLE
wrong template for Merkury MI-BW902-999W

### ISSUE THREAD

**Issue by bosshugo** [blakadder/templates#268]
Hi,

I tried https://templates.blakadder.com/merkury-MI-BW902-999W.html
{"NAME":"MI-BW942-999W","GPIO":[0,0,0,0,37,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":18}
but it doesn't work. I can't turn it on/off and change brightness.

After test, it should be
{"NAME":"MI-BW902-999W","GPIO":[0,0,0,0,0,37,0,0,0,0,0,0,0],"FLAG":0,"BASE":18}
GPIO5 is PWM1

Edward

**Comment by blakadder** [comment]
is the manufacturer id exactly the same?

**Comment by bosshugo** [comment]
Yes, please see attached photo. I bought two kind of this bulb from
Walmart, the RGB one's template is correct. Only this White one, I can't
turn it on. So I tried others and found if I change GPIO to 5 it works.

Edward
[image: IMG_20191229_112905.jpg]
[image: IMG_20191229_112924.jpg]

**Comment by blakadder** [comment]
the template is updated
