### ISSUE TITLE
Not working on 6.5.0

### ISSUE THREAD

**Issue by whatsupskip** [blakadder/templates#28]
I have read elsewhere that the Brilliant unit and the Genio have different configurations. 

Toggling the switch doesn't work, nor does using the switch on the device itself.

**Comment by blakadder** [comment]
I wouldn't know, these are all submitted templates which means they worked for someone. Manufacturers often change the interior design without changing the shell or the product name

**Comment by whatsupskip** [comment]
I have since found that the following template works: {"NAME":"Brilliant","GPIO":[0,0,0,0,0,21,0,0,0,52,90,0,0],"FLAG":0,"BASE":18}. Can this be added to the notes?

**Comment by blakadder** [comment]
it can but i need to know which the device link first

**Comment by whatsupskip** [comment]
The Brilliant WiFi switch with USB charging from Bunnings.
