### ISSUE TITLE
The relay option is not correct

### ISSUE THREAD

**Issue by ashoktvm** [blakadder/templates#289]
In the template, the relay option in GPIO14 should be Relay1 (21) instead of Relay 1i (29). Please change it in template

**Comment by ascillato** [comment]
You have provided zero information. Which device, which config? Please, realize that without information we are not able to guess what are you talking about

**Comment by ashoktvm** [comment]
Sorry my bad. I am talking about the template of this device
https://templates.blakadder.com/thrumm_XS-A11.html

**Comment by ascillato** [comment]
In that case, you can click on edit on github and make that change as a pull request.

**Comment by blakadder** [comment]
Hi!

Changed the template. Thanks!
