### ISSUE TITLE
[Site issue] Missing button for Cocoon Smart LED Strip

### ISSUE THREAD

**Issue by ruddj** [blakadder/templates#290]
The template for Cocoon Smart is missing an assignment for the push button on GPIO0
https://templates.blakadder.com/cocoon_smart_led_strip.html
_templates/cocoon_smart_led_strip

Correct template is:
{"NAME":"Cocoon Smart","GPIO":[17,0,0,0,37,0,0,0,38,0,39,0,0],"FLAG":0,"BASE":18}

Thank you.

**Comment by blakadder** [comment]
Fixed! Thank you.
