### ISSUE TITLE
Earykong TYMC-1 Door Window Sensor 

### ISSUE THREAD

**Issue by HTPCanwender** [blakadder/templates#301]
For support with Tasmota flashing and configuring the device visit [Tasmota Discord](https://discord.gg/Ks2Kzd4).
For support with Tuya-Convert please use their [GitHub Issues](https://github.com/ct-Open-Source/tuya-convert/issues).

When Tasmota starts, it sends a status report. This report contains the POWER status. Later, when the tuya information is processed, a second POWER information is sent. So every opening or closing of the window generates two messages: First the previous status and then the actual status. To avoid this, I used a second rule to report the power information on a different topic.

`rule2 ON TuyaReceived#Data=55AA0005000501010001000C DO publish2 stat/%topic%/POWERA OFF ENDON ON TuyaReceived#Data=55AA0005000501010001010D DO publish2 stat/%topic%/POWERA ON ENDON`

Is there a possibility to switch off the status report of tasmota on boot instead?

**Comment by blakadder** [comment]
You did it the right way, there's no other option afaik
