### ISSUE TITLE
New version UK-1 of Aisirer UK Smart Plug

### ISSUE THREAD

**Issue by RigsbysCatVienna** [blakadder/templates#308]
Here's the current info for the UK Aisirer Smart Plug :
https://github.com/blakadder/templates/blob/master/_templates/aisirer-JH-G01B

I bought some on 2020-01-06 from the same Amazon Page as is linked in the above page, which states that the model is JH-G01B.

The plugs that I received look identical to the old (I do indeed have two JH-G01B models) except that the model number is now "UK-1". Can send a photo if necessary.

The template for JH-G01B does not work for the UK-1 models, but this one does:
{"NAME":"AISIRER","GPIO":[0,17,0,0,0,0,0,0,0,52,21,0,0],"FLAG":1,"BASE":18}

**Comment by blakadder** [comment]
Thanks, I've added the new version
