### ISSUE TITLE
Help with a similar device

### ISSUE THREAD

**Issue by lordbbk** [blakadder/templates#322]
Dear @blakadder,

I have bought a [similar device](https://www.aliexpress.com/item/4000106473335.html), that was shipped in a package very same like yours, although the voltage meter part of the configuration does not seem to work. Relay, button a led configuration is the same.

Can you tell me how you did figure out the other GPIO-s? I would like to make it work for my Home Assistant setup. After the successfull OTA upgrade I would not stop here.

---[EDIT]---
Just realized that you have already have a configuration for [BSD34](https://github.com/blakadder/templates/blob/master/_templates/BSD34), which I have tried, but does not shows anything for the power consumption/meter, however, this is the 16A version which should have it. (it was not yet shown in your visualization page)

Thanks for your help in advance!

**Comment by blakadder** [comment]
Open it up and trace to which gpio's is the power monitoring chip connected
