### ISSUE TITLE
RGB Lighting

### ISSUE THREAD

**Issue by JoeAstor** [blakadder/templates#33]
RGB lighting is not working on this Template.

**Comment by blakadder** [comment]
you didnt say which template

**Comment by JoeAstor** [comment]
Sorry,
I'm talking about the NEO Coolcam 16A Power Monitoring
With the template shown on

**Comment by blakadder** [comment]
Can0t help you with that, it was submitted that way

**Comment by JoeAstor** [comment]
Yeah, sorry i think i was mislead bye the colors in the middle. Had them laying around for a while. And was trying now with the templates. Great work getting everything together here!! Keep it up :-)
