### ISSUE TITLE
Additional UK Sales link for Bomcosy 600lm RGBCCT Bulb

### ISSUE THREAD

**Issue by RigsbysCatVienna** [blakadder/templates#337]
Bought from Amazon UK and flashed with tuya_convert and with [same template as listed on the existing page](https://templates.blakadder.com/bomcosy_7W.html).

Amazon UK link:
https://www.amazon.co.uk/gp/product/B07MF1W5FK/

**Comment by blakadder** [comment]
thank, i'll add it
