### ISSUE TITLE
BSD01 but your numbers do not work on it

### ISSUE THREAD

**Issue by dfgas** [blakadder/templates#349]
I did tasmota.bin and then set the settings you have and only thing that works in the button. i then found someone else that had some other changes and the led now works but still doesn't turn power on and off. the button responds and the led does something. not sure what. lol

**Comment by dfgas** [comment]
gpio4 is led1i
gpio5 is led2i
gpio12 relay1
gpio13 button1

but like i said, power actually doesn't come on.

**Comment by blakadder** [comment]
did you buy the device from the provided link?

**Comment by dfgas** [comment]
unsure, i just know he bought them from amazon. all of the writing on them match exactly though.

**Comment by blakadder** [comment]
but hardware revisions change so you need to find out the new gpio assignments

**Comment by dfgas** [comment]
how do i do that?

**Comment by ruffle-b** [comment]
Just got one of these and the LED and Button are on different GPIOs to the original template.

If it's any help, here's mine:

{"NAME":"YAGALA SWB3","GPIO":[52,0,0,0,0,23,0,0,21,17,22,24,0],"FLAG":1,"BASE":18}

With this template, the USB is Relay 4 and the button toggles socket 1.

**Comment by dfgas** [comment]
![20200212_055447](https://user-images.githubusercontent.com/747541/74334216-17844e00-4d5f-11ea-8d09-187f6a03d728.jpg)
![20200212_055509](https://user-images.githubusercontent.com/747541/74334226-1b17d500-4d5f-11ea-867e-d3ba3327889d.jpg)
![20200212_055453](https://user-images.githubusercontent.com/747541/74334234-1e12c580-4d5f-11ea-98b0-d213a47d42b5.jpg)
![20200212_055519](https://user-images.githubusercontent.com/747541/74334240-1fdc8900-4d5f-11ea-8025-cb402a2b3d61.jpg)
![20200212_055457](https://user-images.githubusercontent.com/747541/74334246-21a64c80-4d5f-11ea-9e29-fc53dd4a76a1.jpg)

**Comment by dfgas** [comment]
i can try that when i get home unless you think mine is different

**Comment by dfgas** [comment]
on mine the button is changing the on/off in the tasmota firmware but the relay is not turning on and off. same if i use the button in the firmware too

**Comment by ruffle-b** [comment]
I'm surprised there are so many variants of this power strip.

There's a guide here:

https://github.com/arendst/Tasmota/wiki/Configuration-Procedure-for-New-Devices

to working out the GPIOs for a new device. Pretty simple to follow and it's what I used when the original template didn't work.
