### ISSUE TITLE
Gosund Duel Outlet - New Version WP212 (WP2)

### ISSUE THREAD

**Issue by Sawadee2u** [blakadder/templates#37]
Just delivered from Amazon today. Did not receive WP211 but got WP212 instead.
Not sure if this is the correct place for this. If not, feel free to delete.
The template for the Gosund WP211 will not work with this new version (WP212)
It causes reboots to default settings ie. back to IP 192.168.4.1. (at lease for me, 6.5.0 - 2.3.0. and 6.5.12 - 2.4.2)
This works as far as the WP211 templates went (no Energy Monitoring results) just buttons and relays.
{"NAME":"WP212","GPIO":[17,0,0,0,18,0,0,0,21,0,22,0,0],"FLAG":0,"BASE":18}
Would love the get Energy working

**Comment by blakadder** [comment]
yes, its not the same model, even the number is different! you can submit the template through the usual channel
