### ISSUE TITLE
Template not working with bulb Bawoo EUWL122130

### ISSUE THREAD

**Issue by kassim3** [blakadder/templates#379]
Hi,

So I'm pretty new to all this so i might be missing something.
I'm using the following template: 
`{"NAME":"Bawoo","GPIO":[0,0,0,0,140,37,0,0,0,142,141,0,0],"FLAG":0,"BASE":18}`

However after adding the template the bulb restarts and changes to blue, i then see the options to change the colour etc but none of it works. The only thing that works is the on/off button.

I followed the instructions [here](https://github.com/arendst/Tasmota/wiki/Configuration-Procedure-for-New-Devices) up until 2.a and discovered the following:
```
GPIO4/relay1 = white
GPIO5/relay2 = NA
GPIO12/relay3 = green
GPIO13/relay4 = blue
GPIO14/relay5 = red
```

Let me know what other info you require, thanks!

**EDIT**

OK so when using the following options i got it to work however i wasn't able to only have pure white:
```
GPIO4 = pwm4
GPIO12 = pwm2
GPIO13 = pwm3
GPIO14  = pwm1
```

**Comment by balvant813** [comment]
I have same problem. It seems that only 3 GPIOs are active, I tried to find 4th using following trials but could not get RGB and W working. I could get RGW no Blue, RBW no Green etc.
Trials:
`{NAME:Teckin SB50a ,GPIO:[0,0,0,0,37,0,0,0,38,39,40,0,0],FLAG:0,BASE:18}  w g b x`
`{NAME:Teckin SB50c ,GPIO:[0,0,0,0,37,0,0,0,38,39,0,40,0],FLAG:0,BASE:18}  w g b x`
`{NAME:Teckin SB50b ,GPIO:[0,0,0,0,37,0,0,40,38,39,0,0,0],FLAG:0,BASE:18}  w g b x`
`{NAME:Teckin SB50e ,GPIO:[0,0,0,0,37,0,40,0,38,39,0,0,0],FLAG:0,BASE:18}  dead`
`{NAME:Teckin SB50f ,GPIO:[0,0,0,0,37,0,0,0,38,40,0,0,0], FLAG:0,BASE:18}  w g x x`
`{NAME:Teckin SB50g ,GPIO:[0,0,0,0,37,0,0,0,39,40,38,0,0],FLAG:0,BASE:18}  w r g x`          
`{NAME:Teckin SB50h ,GPIO:[0,0,0,0,37,0,0,0, 0,40,38,0,0],FLAG:0,BASE:18}  w r x x`   

`{NAME:Teckin SB50 ,GPIO: [0,0,0,0,37,0,0,0,38,40,39,0,0],FLAG:0,BASE:18}  w g r x`
`{NAME:Teckin SB50a ,GPIO:[0,0,0,0,37,0,0,0,38,39,40,0,0],FLAG:0,BASE:18}  w g b x`       
`{NAME:Teckin SB50i ,GPIO:[0,0,0,0,39,0,0,0,38,40,37,0,0],FLAG:0,BASE:18}  r g w x`       	 
`{NAME:Teckin SB50j ,GPIO:[0,0,0,0,40,0,0,0,38,37,39,0,0],FLAG:0,BASE:18}  b g r x`
`{NAME:Teckin SB50j ,GPIO:[0,0,0,0,38,0,0,0,40,37,39,0,0],FLAG:0,BASE:18}  b w r x`
`{NAME:Teckin SB50k ,GPIO:[0,0,0,0,38,0,0,0,37,40,39,0,0],FLAG:0,BASE:18}  g w r x`
`{NAME:Teckin SB50l ,GPIO:[0,0,0,0,38,0,0,0, 37,0,39, 0,0],FLAG:0,BASE:18}  g w r x`
`{NAME:Teckin SB50s ,GPIO:[0,0,0,0,38,0,0,0, 37,0,39, 0,40],FLAG:0,BASE:18}  g w r x`
`{NAME:Teckin SB50r ,GPIO:[0,0,0,0,38,0,0,0, 37,0,39, 40,0],FLAG:0,BASE:18}  g w r x`
`{NAME:Teckin SB50n ,GPIO:[0,0,0,0,38,0,0,40, 37,0,39, 0,0],FLAG:0,BASE:18} g w r x`
`{NAME:Teckin SB50e ,GPIO:[0,0,0,0,38,0,40,0, 37,0,39, 0,0],FLAG:0,BASE:18}  dead - resets to default module 0`
`{NAME:Teckin SB50m ,GPIO:[0,0,0,0,38,40,0,0, 37,0,39, 0,0],FLAG:0,BASE:18} g w r x`
`{NAME:Teckin SB50o ,GPIO:[0,0,0,40,38,0,0,0, 37,0,39, 0,0],FLAG:0,BASE:18} g w r x`
`{NAME:Teckin SB50p ,GPIO:[0,0,40,0,38,0,0,0, 37,0,39, 0,0],FLAG:0,BASE:18}  g w r x`
`{NAME:Teckin SB50q ,GPIO:[0,40,0,0,38,0,0,0, 37,0,39, 0,0],FLAG:0,BASE:18}  g w r x`
`{NAME:Teckin SB50x ,GPIO:[40,0,0,0,38,0,0,0, 37,0,39, 0,0],FLAG:0,BASE:18}  g w r x`
