### ISSUE TITLE
Gosund SW2 dimmer template doesn't remember last dim value set via touch slider

### ISSUE THREAD

**Issue by qwertangel** [blakadder/templates#385]
Gosund SW2 dimmer doesn't seem to remember last dimmer value set from slider interface. It does remember if dim value is set through MQTT. Any way for it to remember last value set from touch front plate ?

Here is way to reproduce -

1) Turn on SW2 dimmer.
2) Increase or decrease brightness to a new value (not same as original value)
3) Turn switch off
4) Turn switch on and notice dim value. It will be same as from step 1 and not from step 2. (i.e. it doesn't remember last dim value from before switch is turn off)

5) Now change dim value using MQTT to a new value.
6) Turn switch off.
7) Turn switch on and notice dim value. It will be same as value from step 5. (i.e. it remembers last dim value from before switch is turn off)

So behavior is different from slider vs MQTT. So script should remember last value from slider too and not just from MQTT.

**Comment by qwertangel** [comment]
Hi @blakadder , i checked the script on your site, and don't see any changes in script. Is this issue closed because it can't be fixed ?

**Comment by blakadder** [comment]
Noone offered a solution and there have been no other reports of the same bug
