### ISSUE TITLE
New WL-SW01_10 revision

### ISSUE THREAD

**Issue by rradar** [blakadder/templates#403]
Hello,

I recently (February 2020) bought a couple of [WL-SW01_10](https://templates.blakadder.com/WL-SW01_10.html) from two different sellers and found out that they changed some things internally.

I guess the worst part is that they swapped the vertical breakout board and therefor the RX/TX pins are now hardly accesible because they are hidden behind a big elco.

![image](https://user-images.githubusercontent.com/34582688/77553920-53a5e500-6ead-11ea-8b6e-0145545fed38.png)

![image](https://user-images.githubusercontent.com/34582688/77553857-3ec95180-6ead-11ea-94c2-b7b1846be14a.png)

![image](https://user-images.githubusercontent.com/34582688/77554166-9ff12500-6ead-11ea-9bd9-2275587ea8b5.png)

It looks like there are more pin outs on the back side but how to trace them and if RX/TX is available - I don't know? I also can't find Voltage/Ground anymore because the one pointed out in the description are gone :disappointed:

**Comment by blakadder** [comment]
Trace with a multimeter in continuity mode to the esp pins

**Comment by rradar** [comment]
Thank's @blakadder I could trace the VCC/GND Pins and the one labeled 'R' and 'K' on the vertical breakout board. Don't know what the later two are for?

Still no luck with the most important: RX/TX

**Comment by blakadder** [comment]
TX and RX are most likely not on the main PCB, R is relay, K i don't remember what it was for, most likely Key aka button

you can do microsoldering on the chip for tx and rx or desolder the esp module board to get access to the pads

**Comment by rradar** [comment]
Thank's @blakadder for the help. I guess easiest is to de-solder the big elco to gain access to the RX/TX pads on the back of the breakout board or maybe even handcraft a little tool to connect the pins even with the elco in place. I will try and report back. The documentation can then later be updated accordingly my findings...

**Comment by rradar** [comment]
So my solution looks like this: Crab on of this long, stackable pin headers (the wemos d1 mini's include this ones) and bend two of them a little to fit with the RX/TX pads (I took the four pins in the middle out):

![image](https://user-images.githubusercontent.com/34582688/77649680-2b2bf280-6f62-11ea-924d-407521c2e88e.png)

Next step is just to push them a bit against the (isolated) elco and you have nice contact to flash your thing with the usual dupont cables:
![image](https://user-images.githubusercontent.com/34582688/77649752-43037680-6f62-11ea-817e-525962537f1c.png)
