### ISSUE TITLE
[Site issue] Lcamav RGBCCT bulb wrongly described as unsupported?

### ISSUE THREAD

**Issue by pejotigrek** [blakadder/templates#408]
regarding [this page](https://templates.blakadder.com/unsupported/lcamaw.html) about **Lcamav RGBCCT Bulb 9W Bulb.** I bought bulb that uses [similar graphics](https://ae01.alicdn.com/kf/Ua00898359bd84078b2ae0097b4ee42415.jpg) with specification:
Brand Name: MALITAI
Color Temperature: Nature White(3500-5500K)
LED Chip Model: 2835
Voltage: AC90V-265V
Luminous Flux: 500 - 999 Lumens
Shape: Globe
Average Life (hrs): >35000Hrs
Length: 125mm
Item Type: LED Bulbs
Led Bulb Type: Bubble Ball Bulb
LED Chip Brand: Epistar
Certification: ce, FCC, ROHS
Beam Angle(°): 120°
Base Type: E27
Power Tolerance: 1%

it works with template from [BlitzWolf BW-LT21 900lm RGBW Bulb](https://templates.blakadder.com/blitzwolf_BW-LT21.html) all I had to do is go to console and enter `setoption37 24` becase of misplaced colours. I can't change white's temperature [it dims instead] but I guess that "unsupported" means that it shouldn't work at all?

PS. flashed with tuya-convert, bought on aliexpress.

**Comment by blakadder** [comment]
Identical and similar are not the same. 

You are free to submit a template for your bulb once you get it working as it is advertised. Since you didn't post a link I can't tell you more
