### ISSUE TITLE
Wrong template information for device mirabella_genio_I002608

### ISSUE THREAD

**Issue by thedeh** [blakadder/templates#413]
Using the configuration listed under this template (with SetOption37 31 enabled) the device is unresponsive to any control commands (toggle, brightness, hue, etc.). I have confirmed the model number. All I get is a blue light when using this template. Are there any other configuration settings I've missed here?

**Comment by blakadder** [comment]
everything submitted is listed on the page

**Comment by obodnikov** [comment]
Right template is
{"NAME":"BQ05 Valve","GPIO":[17,255,255,255,255,255,0,0,21,157,255,255,255],"FLAG":1,"BASE":18}

**Comment by blakadder** [comment]
> Right template is
> {"NAME":"BQ05 Valve","GPIO":[17,255,255,255,255,255,0,0,21,157,255,255,255],"FLAG":1,"BASE":18}

i don't think this is even remotely related to the same device
