### ISSUE TITLE
BQ05 wrong template information

### ISSUE THREAD

**Issue by obodnikov** [blakadder/templates#431]
Wrong template information on https://templates.blakadder.com/irrigation_timer_BQ05.html
Completely not work
Right one is:

{"NAME":"BQ05","GPIO":[17,255,255,255,255,255,0,0,21,157,255,255,255],"FLAG":1,"BASE":18}

Please update page

For support with Tasmota flashing and configuring the device visit [Tasmota Discord](https://discord.gg/Ks2Kzd4).
For support with Tuya-Convert please use their [GitHub Issues](https://github.com/ct-Open-Source/tuya-convert/issues).

**Comment by blakadder** [comment]
it worked for others, please submit a new v2 template

**Comment by s00500** [comment]
Hey everyone, I agree, the template info was not working for me, using the template provided by this issue it is working fine!
