### ISSUE TITLE
Revised template for Aisirer UK-1

### ISSUE THREAD

**Issue by linker3000** [blakadder/templates#438]
Revised template for Aisirer UK-1

Based on testing and device available on Ebay with preflashed Tasmota:

GPIO0: None
GPIO1: Button1 (17)
GPIO2: None
GPIO3: None
GPIO4: BL0937 CF (134)
GPIO5: HLWBL CF1 (132)
GPIO12: HLWBL SELi (131)
GPIO13: LED1 (52)
GPIO14: Relay1 (21)
GPIO15: None
GPIO16: None
ADC0: Analog (1)

**Comment by blakadder** [comment]
please submit the template in the proper format using `Template` command
