### ISSUE TITLE
Zemismart KS-811 3 Gang

### ISSUE THREAD

**Issue by Fusion-Z** [blakadder/templates#44]
Couple of errors in this template.

Button 3 is not defined, Button 1 has an extra 7 on it and Triple is spelled wrong
`{"NAME":"KS-811 Tripple","GPIO":[255,255,52,255,255,18,255,255,22,21,23,255,177],"FLAG":0,"BASE":18}`

Should be
`{"NAME":"KS-811 Triple","GPIO":[255,255,52,255,19,18,255,255,22,21,23,255,17],"FLAG":0,"BASE":18}`

**Comment by blakadder** [comment]
submit a PR with necessary corrections
