### ISSUE TITLE
Maxcio EOP03-EU template wrong/changed

### ISSUE THREAD

**Issue by toller-kuchen795** [blakadder/templates#444]
I found the following template to be wrong: 
https://github.com/blakadder/templates/blob/master/_templates/maxcio_EOP03-EU

When I used it on the device, it led to a reboot after one or two minutes and the device losing the configuration. 
I found the following template to be working on the EOP03-EU:
{"NAME":"Maxcio EOP03-E","GPIO":[0,0,0,0,56,57,0,0,21,17,22,0,0],"FLAG":0,"BASE":18}

**Comment by blakadder** [comment]
added to the site
