### ISSUE TITLE
3Stone EBE-QPW36 1050lm RGBW Bulb product no longer flashable

### ISSUE THREAD

**Issue by JBarrada** [blakadder/templates#447]
I recently bought the bulb from the [amazon link](https://www.amazon.com/gp/product/B07HR8GT12?tag=blakaddertemp-20) listed in the [template](https://templates.blakadder.com/3stone_EBE-QPW36.html) and attempted to flash via tuya-convert. Unfortunately this didn't work so I assume the "2020 version" they have listed when you follow the link has the OTA upgrade hack patched out.

**Comment by blakadder** [comment]
added a warning. thanks!
