### ISSUE TITLE
NEO Coolcam 16A (new template?)

### ISSUE THREAD

**Issue by localhost61** [blakadder/templates#45]
The Coolcam 16A device I just received from Aliexpress holds a BL0937 instead of a HLW8012.
- As Theo suggested in his response to the [issue](https://github.com/arendst/Sonoff-Tasmota/issues/5945) I had to get consistent Energy values , in [your template](https://blakadder.github.io/templates/neocoolcam_16a.html) that I used, GPIO4=131 should be replaced with GPIO4=134.

- In the same page, it looks like the szneo website is outdated, there is no 16A plug in the catalog, only 10A.

**Comment by blakadder** [comment]
that doesn't mean the current template is not operational for all devices

**Comment by localhost61** [comment]
But it deserves a second template or a side note for new comers. Doesn't it?
It just happens that your template doesn't fully match my device, I sent pictures, I've nothing to compare with previous version, if any.

**Comment by blakadder** [comment]
It seems you have missed the quite large Add new template button on the main page of the site

**Comment by meingraham** [comment]
@localhost61 Xavier, an alternative is to edit the existing template entry (fork it and PR) and add the second template with the respective "Here's template for this class of NEO Coolcam and second template for this class with different power monitoring chip". I had this situation with the Kesen KS-604S. This way there aren't two template entries for the same bulb "model" just the variant templates within that template entry.
