### ISSUE TITLE
Template for blitzwolf_SHP2

### ISSUE THREAD

**Issue by barts2108** [blakadder/templates#452]
I have been able to use tuya-convert to flash the BlitzWolf SHP2. When I used the template on the templates site it did not work [(https://templates.blakadder.com/blitzwolf_SHP2.html)](https://templates.blakadder.com/blitzwolf_SHP2.html)

I have brewed my own template that works with red and blue led, button, and power, voltage, current and of course the relay also works.

My template then looks like this

`{"NAME":"BW-SHP2 16A","GPIO":[0,57,0,17,134,132,0,0,131,56,21,0,0],"FLAG":0,"BASE":45}`

I am not aware of the status on the website, but it looks like it is copied from the BlitzWolf-SHP6 10A version. 

tuya-convert  v2.4.3
tasmota         v8.2.0

**Comment by blakadder** [comment]
added new template
