### ISSUE TITLE
Temperature calibration

### ISSUE THREAD

**Issue by ProfEngr** [blakadder/templates#48]
When I updated to the June 15 dev on the Shelly 1PM the template has a temperature reading. It's reading a bit high 100F sitting on the table next to me. The ambient temp is about 74F and the relay doesn't feel like it's that hot to the touch. Should the sensor be ignored or is there a way to calibrate it reasonably? This could also be a Tasmota issue, but figured I'd post here.

**Comment by blakadder** [comment]
100F is not high at all
