### ISSUE TITLE
Dead Links on templates.blakadder.com

### ISSUE THREAD

**Issue by JeffResc** [blakadder/templates#483]
I've collected a list of dead URLs found on templates.blakadder.com in [this Google Sheet](https://docs.google.com/spreadsheets/d/1vfsfNo2J2PzAosjWdKY23qGpHo2tcS6FrONyBCG2nSw/edit?usp=sharing). These URLs are mostly composed of pages with 404 links that should be updated to where the webpage was moved.

**Comment by blakadder** [comment]
Thanks
