### ISSUE TITLE
KMC 70113 Template Issue

### ISSUE THREAD

**Issue by adrianrego** [blakadder/templates#489]
I purchased a 3 pack of these bulbs from Amazon (link in template page) and successfully flashed all 3 with Tasmota via Tuya-convert.  Model on the box says 70113WC.  However, I believe the template has a few issues.

Template:
https://templates.blakadder.com/kmc_70113.html

Issues:

- Tasmota status is inverted.  When Tasmota displays an OFF status, the bulb is ON and vice-versa.  I've tried flipping PWN1/2 to their inverted options (PWN1i/PWN2i) and have had no luck.

- Tasmota does not provide controls for dimming or changing the color temperature of these bulbs.

2 of the bulbs are running Tasmota 8.3.1 and the other is running 8.1.0.

Any thoughts?  I'm new to this and can't find any information information on these bulbs online.

**Comment by blakadder** [comment]
sound like you didnt apply the template at all

**Comment by adrianrego** [comment]
It's applied as far as I know.  I can toggle the light on/off.

![image](https://user-images.githubusercontent.com/173438/82734098-7e15f200-9ce6-11ea-81c0-39da56f16397.png)
![image](https://user-images.githubusercontent.com/173438/82734104-8706c380-9ce6-11ea-87f6-39b7ad6fedba.png)

**Comment by blakadder** [comment]
it is not applied

**Comment by adrianrego** [comment]
How do I apply it then?  I went into Configure Other, pasted in the template, checked Activate, and hit Save.

**Comment by adrianrego** [comment]
Ok, I see what you mean here.  It's still showing Sonoff Basic Module.  Could there be an issue where the firmware isn't applying/saving the template?

**Comment by adrianrego** [comment]
Seems like it's an issue with the device.  Can't change the module.  Bulb looks like it goes into a bootloop and eventually ends up resetting to default module. Will open an issue in the Tasmota project if I can't make any progress.

Thanks for your help.
