### ISSUE TITLE
Edit BSD29

### ISSUE THREAD

**Issue by AS137430** [blakadder/templates#5]
Please amend
https://blakadder.github.io/templates/bsd29.html to the new template:
"NAME":"BSD29","GPIO":[0,0,0,0,134,132,0,0,21,17,56,131,0],"FLAG":0,"BASE":45}

Energy monitoring GPIOs figured out with help from Adobo from Discord.

**Comment by blakadder** [comment]
Updated!

In the future you can use Edit on GitHub link.
