### ISSUE TITLE
Brilliant 20696/7 Template is incorrect

### ISSUE THREAD

**Issue by murraykessell** [blakadder/templates#501]
I have purchased a few of these bulbs from Bunnings and then used the template on your site, but found I could not turn it off and the colour and brightness controls were reverse.
It should be this.
{"NAME":"Brilliant20696","GPIO":[0,0,0,0,0,0,0,0,38,0,37,0,0],"FLAG":0,"BASE":18}
Also in your Brilliant20697 template you have the name as Brilliant20699
The 20697 is the same as the 20696, but has a B22 base.

**Comment by blakadder** [comment]
fixed
