### ISSUE TITLE
Unable to add new template

### ISSUE THREAD

**Issue by macadamer** [blakadder/templates#51]
Tried to add a Maxcio UK power plug template for model W-UK007 (not the power-monitoring variant already in the Templates list), but the form queried if I was sure the template was correct. Presumably because of the already-present UK007S. Anyhoo, mine came from Amazon, it was Tuya-convertible, and seems to work fine.

Anyway, here it is, hope it's OK.

 {"NAME":"Maxcio","GPIO":[0,17,0,0,0,0,255,255,0,56,21,0,0],"FLAG":0,"BASE":18}

**Comment by blakadder** [comment]
The template is regex checked so something is off either with the template or the regex. Since this is the first time i'm inclined to believe it was the template

**Comment by macadamer** [comment]
Still says "Are you you sure this is the output of Tasmota template command?" Yes, I am. I used the template on another plug and that works fine too. Hmm.

Screenshot from "Configure Template":

<img width="380" alt="Screenshot 2019-06-24 at 12 36 33" src="https://user-images.githubusercontent.com/24938366/60016042-f3afb300-967c-11e9-9fbf-49f68f4b3614.png">

Screenshot fron Console:

<img width="1245" alt="Screenshot 2019-06-24 at 12 37 59" src="https://user-images.githubusercontent.com/24938366/60016126-29ed3280-967d-11e9-88bf-ddf8ce818f79.png">

**Comment by blakadder** [comment]
Don't know what to tell you, I ran the template from the op through the google form and it submitted without errors

**Comment by macadamer** [comment]
Would you mind therefore adding the template to the repository for me please? Could use same pic as the W-UK007S already present. I purchased these plugs from Amazon UK, but looks like they only have the UK007S model here now.
