### ISSUE TITLE
Diffs between geeni-GN-SW003-199 and geeni_GN-SW003-199S?

### ISSUE THREAD

**Issue by scorfman** [blakadder/templates#510]
Are there any practical differences between these two device listings? I have this device and both templates work. However geeni-GN-SW003-199 is my preference. The model on mine is simply GN-SW003.  I am curious about the reason for 2 entries. Any info?

I'm working on an update I'll submit a PR for, including some operational notes, construction, and internal pics.

**Comment by blakadder** [comment]
no idea, they're submitted this way
