### ISSUE TITLE
Blitzwolf SHP10 Power metered version template

### ISSUE THREAD

**Issue by JANogueira** [blakadder/templates#517]
Please add the Power metered version template to the Blitzwolf SHP10 page.
According to this Tasmota fix:
https://github.com/arendst/Tasmota/issues/8175

The template for the Power Metered version (POA6204582), with full support for BL0940, is the following:
`
{"NAME":"BW-SHP10","GPIO":[0,148,0,207,158,21,0,0,0,17,0,0,0],"FLAG":0,"BASE":18}
`

Thanks

**Comment by blakadder** [comment]
please use the Add new device option in the sidebar

**Comment by JANogueira** [comment]
Done. Thanks
