### ISSUE TITLE
eachen-IR-DC6

### ISSUE THREAD

**Issue by johng2001** [blakadder/templates#523]
eachen-IR-DC6  may no longer be   "Can be tuya-converted with tuya convert 1.0."
due to   New PSK format
https://github.com/ct-Open-Source/tuya-convert/issues/483

I was able to convert by soldering and
esptool.py --port /dev/ttyAMA0 write_flash -fs 1MB -fm dout 0x0 tasmota-ir.bin

**Comment by blakadder** [comment]
fixed
