### ISSUE TITLE
blitzwolf bw-rc1 module type

### ISSUE THREAD

**Issue by snip3r05** [blakadder/templates#558]
Hello,

Im not sure if this is with you, but i just flash a blitzwolf bw-rc1 then installed your template but when i get to the part do choose a module type it as 0. my device does not have de DC2120

Best regards

**Comment by blakadder** [comment]
and what is the issue here?

**Comment by snip3r05** [comment]
is it supose to look like this?
![Screenshot_2020-06-30-17-24-43-077_com android chrome](https://user-images.githubusercontent.com/16738802/86152032-80dee080-baf7-11ea-8b45-3a13fced90ee.jpg)

**Comment by blakadder** [comment]
yes
