### ISSUE TITLE
Arlec GLD124HA and GLD060HA flashing issues

### ISSUE THREAD

**Issue by jonaseymour** [blakadder/templates#588]
I've just tried to flash both the Arlec GLD124HA and GLD060HA, and having no luck. Just keeps 'Resending SmartConfig Packets'

Also flashed a few mirabella Genio 1002334 with no such issues, so I'm sure I'm doing the process correctly.

Are we sure that these devices are compatible with tuya-convert? This seems to be the key issue in the psk logs if it helps:
`could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)`

Will post on the tasmota git as well.
Any help appreciated.

**Comment by blakadder** [comment]
Why would you post tuya-convert problems to tasmota github? THere's already a thread about the new encrypted firmware on tuya-convert github
