### ISSUE TITLE
LSC Smart connect template

### ISSUE THREAD

**Issue by lecocqe** [blakadder/templates#592]
Hello,

Button on the device is not working for me with this template:
{"NAME":"LSC Smart Plug","GPIO":[0,0,0,0,56,0,0,0,21,17,0,0,0],"FLAG":0,"BASE":18}

on an other site i found the following that is working:
gpio 4 is LED
gpio 12 is relay
gpio 14 is switch

Source: https://thibmaek.com/post/flashing-esphome-to-lsc-smart-connect-action-switches-power-plugs

**Comment by blakadder** [comment]
so you found what is already displayed in the alternative template? so what seem to be the issue that required opening one?

**Comment by lecocqe** [comment]
Sorry, i was too fast. i forgot to put my glasses ;)
