### ISSUE TITLE
Use both leds on Shelly Plug S Power Monitoring Plug

### ISSUE THREAD

**Issue by FransOv** [blakadder/templates#623]
Using this template for the Shelly Plug S Power Monitoring Plug (https://templates.blakadder.com/shelly_plug_S.html):
{"NAME":"Shelly Plug S","GPIO":[56,255,158,255,255,134,0,0,131,17,132,21,255],"FLAG":2,"BASE":45}
enables the use of the blue led on GPIO2 as link status and the red led on GPIO0 as power status.
This is the way the original Shelly firmware used the leds.

**Comment by blakadder** [comment]
thanks, its been updated
