### ISSUE TITLE
BrilliantSmart 20697 9W 900lm CCT Bulb 

### ISSUE THREAD

**Issue by theboystu** [blakadder/templates#634]
After flashing this bulb I tried both of the templates listed for this model and neither worked

https://templates.blakadder.com/brilliantsmart_20697.html

I played around and got a few others to work (mostly) e.g. https://templates.blakadder.com/kogan-KASB10WB22HA.html

The only issue with using the above is the colour of the bulb (e.g. warm/white) is reversed, not sure how to solve that...

**Comment by ndng28** [comment]
Interesting, I have a similar problem with a different bulb

https://github.com/blakadder/templates/issues/651
