### ISSUE TITLE
[Site issue] How to add unsupported device to the site?

### ISSUE THREAD

**Issue by Oxmaster** [blakadder/templates#659]
I'd like to add a device to the unsupported repo, but I'm not sure how. On https://templates.blakadder.com/new.html you can only add supported device.

**Comment by blakadder** [comment]
![image](https://user-images.githubusercontent.com/5904370/92532747-40a38900-f231-11ea-90d9-ec2dad5fa22e.png)

**Comment by Oxmaster** [comment]
For future reference, you have to be on index page (https://templates.blakadder.com/index.html) and not on https://templates.blakadder.com/unsupported.html to see the button.
