### ISSUE TITLE
Energizer_EIS2-1001-RGB is not flashable, W302 wifi chip is not supported 

### ISSUE THREAD

**Issue by nikolac** [blakadder/templates#663]
I just bought a EIS2-1001-RGB v1.2 from Amazon.com (US). I could not flash it with Tuya convert (non ESP8266 chip found). 

When I opened the device, it's not an ESP device. 

Not sure how this template was added.

**Comment by nikolac** [comment]
PDF of the chip https://fccid.io/2ALCFXO-9769/Internal-Photos/Internal-Photos-4343212.pdf

**Comment by blakadder** [comment]
It was added while the bulb had an ESP chip inside

**Comment by nikolac** [comment]
I see the template was added to unsupported devices, thank you.

**Comment by blakadder** [comment]
yes of course! thanks for informing me
