### ISSUE TITLE
hyleton_336

### ISSUE THREAD

**Issue by harvybob** [blakadder/templates#664]
Hi,

I have just flashed a hyleton_336 power strip, It has 3 uk plugs which toggle correctly, but the 4th device - USB ports are toggling the wrong way. When the GUI says its on, the power is actually off, and when the GUI says is off, the power is actually on.

**Comment by blakadder** [comment]
Invert the relay associated with USB

**Comment by harvybob** [comment]
@blakadder I've done that thanks - just wandered if the template should be updated or is it hit/miss depending on the hardware?

**Comment by blakadder** [comment]
i prefer to mirror the original functionality but people submit templates as they've st it up. 

you can change it since it should be your way
