### ISSUE TITLE
Sonoff ZBBridge: better clarify difference between zigbee2mqtt and ZHA mode

### ISSUE THREAD

**Issue by thatso** [blakadder/templates#669]
As I've recently stumbled upon the fact that Zigbee console configuration is not available in ZHA mode [here](https://github.com/arendst/Tasmota/issues/9352) #9352, please add a warning to the [template description](https://zigbee.blakadder.com/Sonoff_ZBBridge.html) clearly stating this fact to avoid others falling for this.

**Comment by Jason2866** [comment]
The modes is called zigbee2tasmota as written in our docs
