### ISSUE TITLE
Moes 9W 800lm RGBCCT Bulb

### ISSUE THREAD

**Issue by otherippo** [blakadder/templates#673]
Hi, I recently bought this bulb and needed to flash it by hand using a soldering iron (tuya-convert was not working due to new firmware). I'd like to share the needed pins which are not labeled on the board on which the esp sits. Could you add my draft to [this link](https://templates.blakadder.com/moes_WB-J9-RCW-E27-1.html)?

Awesome project btw, helped me a lot!

![Moes 9W 800lm RGBCCT Bulb Pinout](https://user-images.githubusercontent.com/32192721/93939062-83358d00-fd2a-11ea-980b-0db76a9bbc61.png)

**Comment by blakadder** [comment]
done
