### ISSUE TITLE
LSC Smart Power plug v.1 now also contains a WB2S module instead of an esp module

### ISSUE THREAD

**Issue by FransOv** [blakadder/templates#674]
LSC Smart Power plug v.1 (Art.no. 2578685 970761 v1.0) now also contains a WB2S module instead of an esp module.
![20200923_160827](https://user-images.githubusercontent.com/57999223/94137139-41a9fc80-fe66-11ea-96f0-72060cc17b13.jpg)

**Comment by blakadder** [comment]
how is that plug different from the one listed? https://templates.blakadder.com/lsc_smart_connect_power_plug.html

**Comment by FransOv** [comment]
This is a version 1 plug (with screws) and still anWB2S module instead of an esp module. As written now on https://templates.blakadder.com/lsc_smart_connect_power_plug.html, the warning seems to apply only to version 2.

**Comment by blakadder** [comment]
there's an edit feature for each page so it is easy to correct erroneous information
