### ISSUE TITLE
Gosund UP111 Template no longer allowing the physical power button to run

### ISSUE THREAD

**Issue by rssfed23** [blakadder/templates#686]
The template at https://templates.blakadder.com/gosund_UP111.html has worked fine for many Tasmota versions for myself.
However, since updating to 8.5.0 (issue also exists on 8.5.1), the physical power button no longer works to turn the plug on/off when pressed.
All other functions of the plug seem to work fine and can be turned on/off via the Tasmota web UI or MQTT. But when pressed the light will flash on/off but not actually trigger the switch to turn on/off. 

Current template used for reference:
```{"NAME":"Gosund UP111","GPIO":[0,52,0,17,134,132,0,0,131,157,21,0,0],"FLAG":0,"BASE":18}```

In the console log, I see the following when pressing the button:
```stat/smart_plug_UPS/BUTTON1T = {"TRIG":"SINGLE"}```

**Comment by blakadder** [comment]
try `setoption73 0`

**Comment by rssfed23** [comment]
That did the trick! - Thanks I'll close this
