### ISSUE TITLE
dimmer slider and warmth for white slider only

### ISSUE THREAD

**Issue by dasb00ter** [blakadder/templates#69]
I just got the 3 pack for this bulb from costco. With sonoff 6.5.0 Im getting a slider for warm white to cold white and a brightness/dimmer slider but no color slider. Confirmed rgb with color codes that work

**Comment by blakadder** [comment]
don't know which bulb but either the template is wrong or you mixed up the bulbs

**Comment by dasb00ter** [comment]
I just looked at the packaging and confirmed it's the correct upc code. Model # on the bulb 37726. Thanks for confirming I should see a color slider. Do u have 3 sliders for brightness, color and white warmth (2000-5000k)? Thanks for putting out the template it got me going even if it seems a bit wonky for me. I guess the only other thing worth mentioning is the only way I can turn them off in home assistant after setting them up with mqtt is to turn the brightness to zero. In the sonoff console power commands work fine though
