### ISSUE TITLE
[Site issue] - Loratap SC411WSC-EU now uses realtek chip

### ISSUE THREAD

**Issue by sthorley** [blakadder/templates#762]
Hi can the page for the Loratap SC411WSC-EU please be updated to show that recently manufactured versions are now using the Realtek chip and are not able to be used with Tasmota. I explicitly checked that the SC411 had a tasmota template before buying however when I went to flash it I discovered a WR3E chip inside.

Images here: https://imgur.com/a/unTRZZn

**Comment by sthorley** [comment]
In fact if you look at the second aliexpress link it now shows in the specifications that it uses the realtek chip:

"Specification

Input Voltage: 100-250VAC, 50/60Hz
Max Load: 600W
Works with: 4 wires(Earth Wire, Netural Wire, L1, L2) AC motor
App Name: Smart Life, Tuya APP
Voice Control: Amazon Alexa, Google Assistant
Wireless Protocol: Wi-Fi 2.4GHz(can't work with 5Ghz Wi-Fi Band)
**Main Chip: REALTKE RTL8710BN Inside**
Dimensions: 86mm*86mm*35mm"

**Comment by blakadder** [comment]
Yes, seems it's become a common occurence with LoraTap devices to use both
