### ISSUE TITLE
[Site issue]

### ISSUE THREAD

**Issue by SylvainGa** [blakadder/templates#776]
Prime plug model CCRCWFII113PK

Template is wrong for mine (two plugs), With that template, it would auto reset after 40 seconds as if the button is kept pressed. The button itself also do not turn on/off the plug. There is also no 'led1' in mine (confirmed by opening it). This is what works for me:

```
GPIO04 - Led2i
GPIO05 - None
GPIO12 - Relay1
GPIO13 - None
GPIO14 - Button1
```

**Comment by blakadder** [comment]
submit a PR please if you want the template updated
