### ISSUE TITLE
[Site issue] Gosund WP3 v2 Template none-functional

### ISSUE THREAD

**Issue by nate2014jatc** [blakadder/templates#797]
Hello,
I would like to report that the v2 template is not working currently with the Gosund WP3 plug at this time.
By looking at the template in github, I was able to get the `template` instead of the `template9` and this configuration works.

Is this an error with the documentation parsing for the template site, or perhaps an accidental omission?

**Comment by blakadder** [comment]
the system selects a v9 template over the old template

**Comment by nate2014jatc** [comment]
Alrighty then, 
I would still like to report that the template the site is presenting isn't working.

**Comment by blakadder** [comment]
Do you have an alternate one?

**Comment by nate2014jatc** [comment]
One that's listed as `template` instead of `template9` is working fine. 

On December 9, 2020 3:32:11 PM UTC, blakadder <notifications@github.com> wrote:
>Do you have an alternate one?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blakadder/templates/issues/797#issuecomment-741847733

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blakadder** [comment]
and what is the template9 version of it?

**Comment by nate2014jatc** [comment]
Looks like you fixed this with commit `4802a0925c1acc2dad4023c0e59a897f9ba04afc`.
