### ISSUE TITLE
Prime Smart Outlet Outdoor Plug -- Alternate Template v9.2.0

### ISSUE THREAD

**Issue by fourwallz** [blakadder/templates#831]
Current template has Led1 on when wifi connected and Led2i on when either plug is on.

This template has Led1i ON when Relay1 is ON and Led2i ON when Relay2 is ON.
{"NAME":"Prime CCWFIO232PK","GPIO":[0,0,0,321,225,576,0,0,32,224,320,0,0,0],"FLAG":0,"BASE":18}

This also allows single press of Button1 to toggle Relay1 and double press Button1 will toggle Relay2.

**Comment by blakadder** [comment]
added
