### ISSUE TITLE
Power button on the powerstrip does not turn on the outlets

### ISSUE THREAD

**Issue by mrteausa** [blakadder/templates#841]
I have to change the Switch1 to Button1 for the power strip Power button to work correctly.  With the Switch it just latches the Outlet1 and turn off when you release the button.  Is there an option on the Tasmota that I need to apply?  I know Switch respond faster than Button but to use the multipress you need to use the Button to work.

**Comment by blakadder** [comment]
Please direct Tasmota related questions to https://github.com/arendst/Tasmota/discussions
