### ISSUE TITLE
[Site issue] - Updated Template for ATHOM US Plug - preflashed withed with tasmota

### ISSUE THREAD

**Issue by vajonam** [blakadder/templates#859]
Seems that the template needs an update to.

```{"NAME":"PG03-US16A-TAS-1","GPIO":[0,0,0,32,2720,2656,0,0,2624,288,224,0,0,0],"FLAG":0,"BASE":18}```

**Comment by vajonam** [comment]
Model on the Plug shows ```TP16Y```

**Comment by blakadder** [comment]
thanks
