### ISSUE TITLE
Missing template for HiHome WPP-10S2

### ISSUE THREAD

**Issue by lauer** [blakadder/templates#88]
Currently there is a template for HiHome WPP-16T dual plug. 
I have just bought two of those single plug, and would like to flash whose with Tasmota.

I guess it should be possible?

https://github.com/blakadder/templates/blob/master/_templates/hihome_WPP-16T.markdown

**Comment by blakadder** [comment]
I guess...

**Comment by lauer** [comment]
I have 4 of those WPP-10S2, and loaded the WPP-16T template, which shows two buttons where 2. works as relay on the single plug. But it seems like the power watt can not be calibrated correctly.

How can I help finding the correct template for this plug?
