### ISSUE TITLE
[Site issue] BrilliantSmart 20698 and 20698 9W 800lm RGBW Bulb

### ISSUE THREAD

**Issue by DeanCording** [blakadder/templates#905]
Both the BrilliantSmart 20698 (E27) and 20699 (B22) RGBW bulbs now use the WB2L Wifi module and can no longer be reflashed with Tasmota.  Please change them to Unsupported as they are being heavily promoted by a big box hardware store here in Australia.

**Comment by blakadder** [comment]
added
