### ISSUE TITLE
[Site issue] Broken image on Sonoff Basic page

### ISSUE THREAD

**Issue by njh** [blakadder/templates#909]
On this page:
https://templates.blakadder.com/sonoff_basic.html

There is a broken image in the section "Sonoff Basic R1".

> Image re-used from https://www.instructables.com/id/Use-Homie-Firmware-to-Drive-Sonoff-Switch-Module-E/ Thanks @amayii0

The image URL is:
https://cdn.instructables.com/F8Q/0U89/J1WEQK7J/F8Q0U89J1WEQK7J.MEDIUM.jpg

I am not sure if the image URL has changed or Instructables are trying to prevent people using their images on other web pages. The error message is "Access Denied" - but I think S3 sometimes returns this rather than 404.

**Comment by blakadder** [comment]
![image](https://user-images.githubusercontent.com/5904370/106366823-bf16d980-633e-11eb-883b-a9283fef4fb5.png)

fixing
