### ISSUE TITLE
teckin_SB50_v2 Template should have 5 channels RGBCCT

### ISSUE THREAD

**Issue by Bbas11** [blakadder/templates#958]
According to the picture it has rbg leds cw and ww and should be {"NAME":"Teckin SB50v3","GPIO":[0,0,0,0,416,419,0,0,417,420,418,0,0,0],"FLAG":0,"BASE":18} Or maybe the pictures are reversed with the V3

**Comment by blakadder** [comment]
do you mean this bulb https://templates.blakadder.com/teckin_SB50_v2.html ?

**Comment by Bbas11** [comment]
Yes, I think the only problem the pictures are reversed between that one and the SB50-V3

**Comment by blakadder** [comment]
Do you have an example of the differences?
