### ISSUE TITLE
Template update: KMC 5AC 3USB QC Power Strip

### ISSUE THREAD

**Issue by Dan-Wilder** [blakadder/templates#960]
Updating the template to `{"NAME":"KMC 5-Outlet","GPIO":[320,0,0,0,228,32,0,0,225,224,226,0,227,0],"FLAG":0,"BASE":18}` *or* setting GPIO5 to Button 1 instead of Switch 1 will enable proper multi-press functionality with the power button.

**Comment by blakadder** [comment]
please edit the appropriate template instead of submitting an issue
