### ISSUE TITLE
Maxcio 400ml Aromatherapy Diffuser hardware change

### ISSUE THREAD

**Issue by madman2143** [blakadder/templates#999]
It seems that the chipset on this device has changed and therefor it is no longer easily flashable. The new micro controller is the WBR3, sadly not based on an esp chipset. 

https://developer.tuya.com/en/docs/iot/device-development/module/wifibt-dual-mode-module/wbr-series-module/wbr3-module-datasheet?id=K9dujs2k5nriy

I bought the device this week on german Amazon.
<img width="719" alt="wbr3" src="https://user-images.githubusercontent.com/67551791/114607578-0275b880-9c9d-11eb-83b1-f5ce4fc9e48d.png">

Sorry if this is the wrong place to post this info.

**Comment by blakadder** [comment]
upadted the template page
